//! ROM regression harness (Track C — Task 1 / C-2).
//!
//! Re-implements the functionality of the original C++ `rom_regression_test.cpp`
//! in pure Rust. For each test ROM, the harness:
//!
//! 1. Loads the ROM via [`SutAdapter::load`].
//! 2. Runs `FRAMES_TO_RUN = 60` frames via [`SutAdapter::step`].
//! 3. After each frame, copies the visible 256x240 region of XBuf
//!    (61440 bytes) into a local buffer via [`SutAdapter::snapshot`]
//!    and computes the CRC32 of that buffer.
//! 4. Compares the collected hash sequence against the entry in
//!    `fixtures/golden_hashes.json` and reports any mismatches.
//!
//! Mirrors the C++ behaviour at `tests/rom_regression_test.cpp:189-330`:
//! - `setvbuf(stdout, NULL, _IONBF, 0)` — already handled by Rust stdio.
//! - Loads each ROM in the hard-coded `tests[]` table.
//! - 60 frames per ROM, CRC32 of `XBuf[0..256*240]` per frame.
//! - Compares against `fixtures/golden_hashes.json`; mismatches print
//!   up to 5 lines and bump the global `mismatches` counter.
//! - Exit 0 iff every ROM matches; otherwise exit 1.
//!
//! ## Schema freeze
//!
//! The harness does NOT introduce new manifest fields. It uses the
//! existing `tests.json` schema for invocation metadata (CTest name,
//! binary, args, expected exit code) and the existing
//! `golden_hashes.json` format (`name → { frames: [u32; 60] }`).
//!
//! ## CRC32 implementation
//!
//! The Rust side uses the existing `crc32fast` crate (already a
//! dependency of `fceux11-utils`, transitively available to
//! `kagami-qa`). The CRC polynomial matches IEEE 802.3 (same as the
//! C++ `CalcCRC32` -> `fceux11_rust_crc32` -> `crc32fast::Hasher` chain
//! at `src/utils/crc32.cpp:23-30`). Byte-identical results for any
//! given input.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use crate::adapter::trait_def::SutAdapter;
use crate::core::QaError;

/// Width of the visible XBuf region (matches rom_regression_test.cpp:14).
pub const FRAME_WIDTH: usize = 256;
/// Height of the visible XBuf region (matches rom_regression_test.cpp:15).
pub const FRAME_HEIGHT: usize = 240;
/// Visible XBuf region size in bytes.
pub const FRAME_BUF_SIZE: usize = FRAME_WIDTH * FRAME_HEIGHT;
/// Number of frames per ROM (matches rom_regression_test.cpp:16).
pub const FRAMES_TO_RUN: u32 = 60;

/// One entry in the hard-coded ROM table (mirrors `RomTestCase`
/// in `tests/rom_regression_test.cpp:18-38`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RomRegressionCase {
    pub filename: String,
    pub name: String,
}

/// The canonical 13-ROM table from `rom_regression_test.cpp:24-37`.
///
/// Returned as `&'static [RomRegressionCase]` so callers can iterate
/// without copying. Initialised once via `OnceLock` so the `String`
/// fields are owned exactly once.
pub fn rom_regression_cases() -> &'static [RomRegressionCase] {
    use std::sync::OnceLock;
    static CELL: OnceLock<Vec<RomRegressionCase>> = OnceLock::new();
    CELL.get_or_init(|| {
        vec![
            RomRegressionCase { filename: "fixtures/mapper_nrom.nes".into(),        name: "nrom".into() },
            RomRegressionCase { filename: "fixtures/mapper_mmc1.nes".into(),        name: "mmc1".into() },
            RomRegressionCase { filename: "fixtures/mapper_uxrom.nes".into(),       name: "uxrom".into() },
            RomRegressionCase { filename: "fixtures/mapper_cnrom.nes".into(),       name: "cnrom".into() },
            RomRegressionCase { filename: "fixtures/mapper_mmc3.nes".into(),        name: "mmc3".into() },
            RomRegressionCase { filename: "fixtures/mapper_mmc5.nes".into(),        name: "mmc5".into() },
            RomRegressionCase { filename: "fixtures/mapper_axrom.nes".into(),       name: "axrom".into() },
            RomRegressionCase { filename: "fixtures/mapper_colordreams.nes".into(), name: "colordreams".into() },
            RomRegressionCase { filename: "fixtures/mapper_gnrom.nes".into(),       name: "gnrom".into() },
            RomRegressionCase { filename: "fixtures/mapper_vrc2and4.nes".into(),    name: "vrc2and4".into() },
            RomRegressionCase { filename: "fixtures/mapper_vrc6.nes".into(),        name: "vrc6".into() },
            RomRegressionCase { filename: "fixtures/mapper_vrc7.nes".into(),        name: "vrc7".into() },
            RomRegressionCase { filename: "fixtures/nestest.nes".into(),            name: "nestest".into() },
        ]
    })
}

/// Parsed view of a `golden_hashes.json` document.
///
/// Matches the C++ `readGoldenHashes` parser (rom_regression_test.cpp:49-145).
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct GoldenHashes {
    pub names: Vec<String>,
    pub frames: Vec<Vec<u32>>,
}

impl GoldenHashes {
    /// Parse the JSON document. Hand-rolled to mirror the C++ reader —
    /// the format is constrained (the file is generated by the same
    /// C++ writer, never edited by hand).
    ///
    /// State machine:
    ///
    /// ```text
    ///   Top ──{──▶ InObject ──"name"──▶ InObject (record name)
    ///                              ──"frames"──▶ ExpectingArray
    ///                                         ──[──▶ InArray
    ///                                                  ──num──▶ InArray
    ///                                                  ──]──▶ InObject
    ///                                                  ──}──▶ Top (record entry)
    /// ```
    ///
    /// The outer `{` puts us in `InObject` (where we look for ROM keys).
    /// The inner `{` is a no-op (we are still in `InObject`; the next
    /// `"frames"` key is what advances us to `ExpectingArray`).
    pub fn parse(json: &str) -> Self {
        let mut out = GoldenHashes::default();
        let mut chars = json.chars().peekable();
        let mut current_name = String::new();
        let mut current_frames: Vec<u32> = Vec::new();
        let mut in_string = false;
        let mut token = String::new();
        let mut state = ParseState::Top;

        while let Some(c) = chars.next() {
            // Inside a string: accumulate until closing quote.
            if in_string {
                if c == '"' {
                    in_string = false;
                    match state {
                        ParseState::Top | ParseState::InObject => {
                            // We just finished reading a key. If it's
                            // "frames", the next token is the array.
                            if token == "frames" {
                                state = ParseState::ExpectingArray;
                            } else {
                                // ROM name (key in the outer object).
                                current_name = token.clone();
                            }
                        }
                        ParseState::ExpectingArray => {
                            // The "frames" key was a known marker; we
                            // never reach ExpectingArray with another
                            // token, so this branch is unreachable.
                        }
                        ParseState::InArray => {
                            // Numbers come unquoted; this branch is
                            // also unreachable.
                        }
                    }
                } else {
                    token.push(c);
                }
                continue;
            }

            match c {
                '"' => {
                    in_string = true;
                    token.clear();
                }
                '{' => {
                    // Outer { or inner { — both leave us in InObject
                    // (the next token determines whether it's a ROM
                    // name or "frames").
                    state = ParseState::InObject;
                }
                '}' => {
                    // End of an object. If we have a name+frames, save
                    // them. State goes back to Top because the outer
                    // document is closing OR we just finished the inner
                    // object of the previous ROM. The next thing is
                    // either `,` (whitespace) or another key.
                    if !current_name.is_empty() {
                        out.names.push(current_name.clone());
                        out.frames.push(current_frames.clone());
                        current_name.clear();
                        current_frames.clear();
                    }
                    state = ParseState::Top;
                }
                '[' => {
                    if state == ParseState::ExpectingArray {
                        current_frames.clear();
                        state = ParseState::InArray;
                    }
                }
                ']' => {
                    if state == ParseState::InArray {
                        state = ParseState::InObject;
                    }
                }
                ',' | ':' | ' ' | '\t' | '\n' | '\r' => {
                    // Whitespace / structural punctuation: ignored.
                }
                c if c.is_ascii_digit() => {
                    if state == ParseState::InArray {
                        let mut num = String::new();
                        num.push(c);
                        while let Some(&nc) = chars.peek() {
                            if nc.is_ascii_digit() {
                                num.push(nc);
                                chars.next();
                            } else {
                                break;
                            }
                        }
                        if let Ok(v) = num.parse::<u32>() {
                            current_frames.push(v);
                        }
                    }
                }
                _ => {
                    // Unknown character — silently skip (mirrors C++
                    // permissive parser).
                }
            }
        }
        out
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ParseState {
    Top,
    InObject,
    ExpectingArray,
    InArray,
}

#[cfg(test)]
mod parse_state_tests {
    use super::*;
    #[test]
    fn parse_state_default_is_top() {
        assert_eq!(ParseState::Top, ParseState::Top);
    }
}

/// Outcome of running the rom_regression harness once.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RomRegressionOutcome {
    /// Per-ROM CRC32 sequences collected from the harness.
    pub collected: BTreeMap<String, Vec<u32>>,
    /// Mismatches (rom_name → vec of (frame_idx, expected, actual)).
    pub mismatches: Vec<RomRegressionMismatch>,
    /// Total frames compared (sum of common length across all ROMs).
    pub total_compared: u32,
    /// True iff at least one ROM had no baseline entry.
    pub missing_baseline: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RomRegressionMismatch {
    pub rom_name: String,
    pub frame: usize,
    pub expected: u32,
    pub actual: u32,
}

/// CRC32 over a byte slice using the IEEE 802.3 polynomial. Equivalent
/// to `CalcCRC32(0, buf, len)` in the C++ harness.
pub fn crc32(buf: &[u8]) -> u32 {
    crc32_update(0, buf)
}

/// CRC32 with an explicit initial value (matches `CalcCRC32(crc, buf, len)`).
pub fn crc32_update(crc: u32, buf: &[u8]) -> u32 {
    let mut h = crc32fast::Hasher::new_with_initial(crc);
    h.update(buf);
    h.finalize()
}

// ---------------------------------------------------------------------------
// Adapter abstraction — Track C adds `extract_frame_buffer` to the FFI
// bridge but NOT to the SutAdapter trait (Stage-3 freeze: no new
// methods). Instead, this module calls the FFI directly via the
// `extract_via_ffi` helper, which is only available when the
// `direct-adapter` feature is enabled. Unit tests use a mocked
// `FrameSource` that implements the same protocol via the existing
// `snapshot()` method (already part of SutAdapter).
// ---------------------------------------------------------------------------

/// Per-frame CRC32 collector. Drives the adapter and returns the
/// collected sequence. Used in production (where `frame_source` is the
/// `Fceux11DirectAdapter`) and in tests (where it's a mock).
pub fn collect_frame_crcs<A>(
    adapter: &mut A,
    case: &RomRegressionCase,
    workdir: &Path,
    frame_count: u32,
) -> Result<Vec<u32>, QaError>
where
    A: SutAdapter + FrameSource,
{
    let rom_path = resolve_rom_path(workdir, &case.filename);
    let spec = crate::adapter::trait_def::InputSpec {
        rom_path: Some(rom_path.to_string_lossy().to_string()),
        script_path: None,
        frames: frame_count,
        probe_addr: 0x6000,
        reset_after: -1,
    };
    adapter.load(&spec)?;

    let mut buf = vec![0u8; FRAME_BUF_SIZE];
    let mut crcs = Vec::with_capacity(frame_count as usize);
    for _frame in 0..frame_count {
        adapter.step()?;
        adapter.extract_frame(&mut buf)?;
        crcs.push(crc32(&buf));
    }
    let _ = adapter.reset();
    Ok(crcs)
}

/// Resolves a relative ROM path against `workdir`, returning an
/// absolute path. Mirrors the C++ implicit behaviour: tests are run
/// with `WORKING_DIRECTORY = tests/`, so `fixtures/mapper_nrom.nes`
/// resolves to `tests/fixtures/mapper_nrom.nes`.
fn resolve_rom_path(workdir: &Path, rel: &str) -> PathBuf {
    let p = Path::new(rel);
    if p.is_absolute() {
        p.to_path_buf()
    } else {
        workdir.join(p)
    }
}

/// Trait implemented by anything that can produce the per-frame
/// visible XBuf region. The production `Fceux11DirectAdapter`
/// implements this via the new `kagami_bridge_extract_frame_buffer` FFI;
/// mocks implement it directly for unit tests. This is the minimal
/// shape Track C needs without violating the Stage-3 "no new
/// SutAdapter methods" rule.
pub trait FrameSource {
    fn extract_frame(&self, buf: &mut [u8]) -> Result<(), QaError>;
}

#[cfg(any(feature = "direct-adapter", not(test)))]
impl FrameSource for crate::adapter::direct::Fceux11DirectAdapter {
    fn extract_frame(&self, buf: &mut [u8]) -> Result<(), QaError> {
        if buf.len() != FRAME_BUF_SIZE {
            return Err(QaError::unsupported(format!(
                "extract_frame: expected {} bytes, got {}",
                FRAME_BUF_SIZE,
                buf.len()
            )));
        }
        let rc = unsafe {
            kagami_bridge_extract_frame_buffer(buf.as_mut_ptr(), buf.len() as u32)
        };
        if rc != 0 {
            return Err(QaError::unsupported(format!(
                "kagami_bridge_extract_frame_buffer failed: rc={}",
                rc
            )));
        }
        Ok(())
    }
}

// FFI declaration (mirrors adapter/direct.rs but is `pub(crate)` so it
// can be used by both adapter::direct and runner::rom_regression
// without re-declaring). Marked unsafe to keep callers honest.
#[cfg(any(feature = "direct-adapter", not(test)))]
unsafe extern "C" {
    fn kagami_bridge_extract_frame_buffer(dst: *mut u8, len: u32) -> i32;
}

// ---------------------------------------------------------------------------
// High-level runner.
// ---------------------------------------------------------------------------

/// Run the full harness against the supplied `GoldenHashes` baseline.
///
/// `workdir` is the directory in which `fixtures/...` paths resolve
/// (typically the `tests/` directory). `frame_source` produces the
/// per-frame XBuf region.
pub fn run_regression<A>(
    adapter: &mut A,
    golden: &GoldenHashes,
    workdir: &Path,
) -> RomRegressionOutcome
where
    A: SutAdapter + FrameSource,
{
    let mut collected: BTreeMap<String, Vec<u32>> = BTreeMap::new();
    let mut mismatches: Vec<RomRegressionMismatch> = Vec::new();
    let mut total_compared: u32 = 0;
    let mut missing_baseline: Vec<String> = Vec::new();

    for case in rom_regression_cases() {
        let path = resolve_rom_path(workdir, &case.filename);
        let crcs = match collect_frame_crcs(adapter, case, workdir, FRAMES_TO_RUN) {
            Ok(v) => v,
            Err(_) => {
                // C++ continues on ROM load failure (sets anyFailed = true).
                // Mirror that: record a "missing" entry so the run is
                // marked failed but the loop continues.
                missing_baseline.push(case.name.clone());
                continue;
            }
        };
        collected.insert(case.name.clone(), crcs.clone());

        let exp_idx = golden.names.iter().position(|n| n == &case.name);
        match exp_idx {
            None => missing_baseline.push(case.name.clone()),
            Some(idx) => {
                let expected = &golden.frames[idx];
                let compare = crcs.len().min(expected.len());
                for f in 0..compare {
                    total_compared += 1;
                    if crcs[f] != expected[f] {
                        if mismatches.len() < 5 {
                            mismatches.push(RomRegressionMismatch {
                                rom_name: case.name.clone(),
                                frame: f,
                                expected: expected[f],
                                actual: crcs[f],
                            });
                        }
                    }
                }
            }
        }
        let _ = path; // referenced for documentation; not used otherwise
    }

    RomRegressionOutcome {
        collected,
        mismatches,
        total_compared,
        missing_baseline,
    }
}

/// Format the regression summary the way the C++ harness prints it
/// (`printf("=== Results ===\n"); printf("Compared: %d frames\n", ...);`).
pub fn format_summary(outcome: &RomRegressionOutcome) -> String {
    let mut s = String::new();
    s.push_str("=== Results ===\n");
    s.push_str(&format!("Compared: {} frames\n", outcome.total_compared));
    s.push_str(&format!("Mismatches: {}\n", outcome.mismatches.len()));
    if !outcome.missing_baseline.is_empty() {
        s.push_str(&format!("Missing baseline for: {}\n", outcome.missing_baseline.join(", ")));
    }
    if outcome.mismatches.is_empty() && outcome.missing_baseline.is_empty() {
        s.push_str("RESULT: PASSED\n");
    } else {
        s.push_str("RESULT: FAILED\n");
    }
    s
}

pub fn regression_exit_code(outcome: &RomRegressionOutcome) -> i32 {
    if outcome.mismatches.is_empty() && outcome.missing_baseline.is_empty() {
        0
    } else {
        1
    }
}

/// Load `golden_hashes.json` from disk and parse it.
pub fn load_golden_hashes(path: &Path) -> Result<GoldenHashes, String> {
    let text = std::fs::read_to_string(path)
        .map_err(|e| format!("cannot read golden hashes '{}': {}", path.display(), e))?;
    Ok(GoldenHashes::parse(&text))
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::adapter::trait_def::{InputSpec, SutAdapter, TestResult};
    use crate::core::{ErrorKind, QaConfig, QaError};
    use crate::manifest::schema::TestManifest;

    /// Mock adapter that returns a fixed XBuf pattern per step,
    /// counting calls. Implements both SutAdapter and FrameSource.
    struct MockAdapter {
        pattern: u8,
        step_count: u32,
        loaded: Option<String>,
        reset_calls: u32,
        frame_fail_at: Option<u32>,
    }

    impl MockAdapter {
        fn new(pattern: u8) -> Self {
            Self {
                pattern,
                step_count: 0,
                loaded: None,
                reset_calls: 0,
                frame_fail_at: None,
            }
        }
    }

    impl SutAdapter for MockAdapter {
        fn init(&self, _config: &QaConfig) -> Result<(), QaError> {
            Ok(())
        }
        fn run_test(&self, _test: &TestManifest) -> Result<TestResult, QaError> {
            unimplemented!()
        }
        fn load(&mut self, input: &InputSpec) -> Result<(), QaError> {
            self.loaded = input.rom_path.clone();
            Ok(())
        }
        fn step(&mut self) -> Result<(), QaError> {
            if Some(self.step_count) == self.frame_fail_at {
                return Err(QaError {
                    kind: ErrorKind::TestExecFailed,
                    message: "step limit hit".into(),
                });
            }
            self.step_count += 1;
            Ok(())
        }
        fn read_oracle_probe(&self, _addr: u32) -> Result<u8, QaError> {
            Ok(0)
        }
        fn reset(&mut self) -> Result<(), QaError> {
            self.reset_calls += 1;
            Ok(())
        }
    }

    impl FrameSource for MockAdapter {
        fn extract_frame(&self, buf: &mut [u8]) -> Result<(), QaError> {
            // Deterministic but frame-varying pattern: byte i = pattern ^ step_count.
            for (i, b) in buf.iter_mut().enumerate() {
                *b = self.pattern ^ (self.step_count as u8) ^ (i as u8 & 0x0F);
            }
            Ok(())
        }
    }

    // ---------------- CRC32 parity tests ---------------------------------

    #[test]
    fn crc32_matches_known_value_for_empty() {
        assert_eq!(crc32(&[]), 0);
    }

    #[test]
    fn crc32_matches_known_value_for_ascii() {
        // Known CRC32 of "123456789" is 0xCBF43926 (IEEE 802.3).
        assert_eq!(crc32(b"123456789"), 0xCBF43926);
    }

    #[test]
    fn crc32_matches_known_value_for_256_byte_zero_buffer() {
        // CRC32 of 256 zero bytes, computed by crc32fast (reference).
        let buf = vec![0u8; 256];
        let expected = crc32fast::hash(&buf);
        assert_eq!(crc32(&buf), expected);
    }

    #[test]
    fn crc32_update_chains_match_single_call() {
        let buf = b"The quick brown fox";
        let whole = crc32(buf);
        let (a, b) = buf.split_at(10);
        let chunked = crc32_update(crc32_update(0, a), b);
        assert_eq!(whole, chunked);
    }

    // ---------------- Golden hash parsing --------------------------------

    #[test]
    fn parse_golden_hashes_minimal() {
        let json = r#"{
            "nrom": { "frames": [1, 2, 3] },
            "mmc1": { "frames": [4, 5, 6] }
        }"#;
        let g = GoldenHashes::parse(json);
        assert_eq!(g.names.len(), 2);
        assert_eq!(g.names[0], "nrom");
        assert_eq!(g.frames[0], vec![1, 2, 3]);
        assert_eq!(g.names[1], "mmc1");
        assert_eq!(g.frames[1], vec![4, 5, 6]);
    }

    #[test]
    fn parse_golden_hashes_real_file() {
        // Read the actual fixture; this must not panic and must produce
        // the expected 13 entries.
        // CARGO_MANIFEST_DIR points to src/rust/crates/kagami-qa/, so we
        // go up 4 levels to reach the worktree root, then into
        // tests/fixtures/. The C++ harness reads from there via
        // WORKING_DIRECTORY = tests/.
        let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
            .unwrap_or_else(|_| String::from("."));
        let p = PathBuf::from(manifest_dir)
            .join("..")
            .join("..")
            .join("..")
            .join("..")
            .join("tests")
            .join("fixtures")
            .join("golden_hashes.json");
        if !p.exists() {
            // Skip gracefully when the fixture isn't checked out (rare
            // in CI sandboxes).
            eprintln!("skipping parse_golden_hashes_real_file: fixture missing at {}", p.display());
            return;
        }
        let g = load_golden_hashes(&p).unwrap();
        eprintln!("parsed names: {:?}", g.names);
        // The C++ test has 13 cases (12 mappers + nestest), each with
        // 60 frame hashes.
        assert_eq!(g.names.len(), 13);
        for frames in &g.frames {
            assert_eq!(frames.len(), 60);
        }
    }

    // ---------------- Per-ROM collection ---------------------------------

    #[test]
    fn collect_frame_crcs_produces_60_entries() {
        let mut a = MockAdapter::new(0x55);
        let case = RomRegressionCase {
            filename: "fixtures/x.nes".into(),
            name: "x".into(),
        };
        let crcs = collect_frame_crcs(&mut a, &case, Path::new("."), 60).unwrap();
        assert_eq!(crcs.len(), 60);
        // Different frames → different CRCs (the mock varies pattern by step).
        assert_ne!(crcs[0], crcs[1]);
    }

    #[test]
    fn collect_frame_crcs_uses_expected_frame_count() {
        let mut a = MockAdapter::new(0);
        let case = RomRegressionCase {
            filename: "fixtures/x.nes".into(),
            name: "x".into(),
        };
        let crcs = collect_frame_crcs(&mut a, &case, Path::new("."), 10).unwrap();
        assert_eq!(crcs.len(), 10);
    }

    #[test]
    fn collect_frame_crcs_step_error_aborts() {
        let mut a = MockAdapter::new(0);
        a.frame_fail_at = Some(5);
        let case = RomRegressionCase {
            filename: "fixtures/x.nes".into(),
            name: "x".into(),
        };
        let r = collect_frame_crcs(&mut a, &case, Path::new("."), 60);
        assert!(r.is_err());
    }

    // ---------------- Regression runner -----------------------------------

    #[test]
    fn regression_passes_when_golden_matches() {
        // Use a MockAdapter that returns a deterministic CRC per frame.
        // The mock's pattern is fixed; we compute the expected CRCs
        // ourselves and inject them into the golden table for the ROM
        // name that the regression runner actually iterates over.
        let mut probe = MockAdapter::new(0x55);
        let case = RomRegressionCase {
            filename: "fixtures/mapper_nrom.nes".into(),
            name: "nrom".into(),
        };
        let crcs = collect_frame_crcs(&mut probe, &case, Path::new("."), 60).unwrap();
        let golden = GoldenHashes {
            names: vec!["nrom".into()],
            frames: vec![crcs.clone()],
        };
        // Fresh adapter for the regression run so that step_count
        // starts from 0 and the same CRC sequence is reproduced.
        let mut a = MockAdapter::new(0x55);
        let outcome = run_regression(&mut a, &golden, Path::new("."));
        // Only one of the 13 cases matches by name. The other 12 will
        // be reported as missing baseline. total_compared reflects the
        // single matching case.
        assert_eq!(outcome.total_compared, 60);
        assert!(outcome.mismatches.is_empty());
        // 12 missing baselines ⇒ exit code 1 (FAIL).
        assert_eq!(outcome.missing_baseline.len(), 12);
        assert_eq!(regression_exit_code(&outcome), 1);
    }

    #[test]
    fn regression_flags_first_few_mismatches() {
        let mut probe = MockAdapter::new(0x55);
        let case = RomRegressionCase {
            filename: "fixtures/mapper_nrom.nes".into(),
            name: "nrom".into(),
        };
        let mut crcs = collect_frame_crcs(&mut probe, &case, Path::new("."), 60).unwrap();
        crcs[10] = 0xDEADBEEF;
        crcs[20] = 0xCAFEBABE;
        let golden = GoldenHashes {
            names: vec!["nrom".into()],
            frames: vec![crcs.clone()],
        };
        let mut a = MockAdapter::new(0x55);
        let outcome = run_regression(&mut a, &golden, Path::new("."));
        assert_eq!(outcome.mismatches.len(), 2);
        assert_eq!(outcome.mismatches[0].frame, 10);
        assert_eq!(outcome.mismatches[1].frame, 20);
        assert_eq!(regression_exit_code(&outcome), 1);
    }

    #[test]
    fn regression_missing_baseline_marks_fail() {
        let mut a = MockAdapter::new(0x55);
        let golden = GoldenHashes::default();
        let outcome = run_regression(&mut a, &golden, Path::new("."));
        // 13 cases total in ROM_REGRESSION_CASES — none have a baseline.
        assert_eq!(outcome.missing_baseline.len(), 13);
        assert_eq!(regression_exit_code(&outcome), 1);
    }

    #[test]
    fn regression_summary_text_matches_cxx() {
        let outcome = RomRegressionOutcome {
            collected: BTreeMap::new(),
            mismatches: vec![],
            total_compared: 720,
            missing_baseline: vec![],
        };
        let s = format_summary(&outcome);
        assert!(s.contains("=== Results ==="));
        assert!(s.contains("Compared: 720 frames"));
        assert!(s.contains("Mismatches: 0"));
        assert!(s.contains("RESULT: PASSED"));
    }

    #[test]
    fn regression_summary_text_on_failure() {
        let outcome = RomRegressionOutcome {
            collected: BTreeMap::new(),
            mismatches: vec![RomRegressionMismatch {
                rom_name: "nrom".into(),
                frame: 0,
                expected: 0xCAFEBABE,
                actual: 0xDEADBEEF,
            }],
            total_compared: 60,
            missing_baseline: vec![],
        };
        let s = format_summary(&outcome);
        assert!(s.contains("RESULT: FAILED"));
        assert!(s.contains("Mismatches: 1"));
    }

    // ---------------- Constants / table -----------------------------------

    #[test]
    fn rom_table_matches_cxx_size() {
        // C++ table has 13 entries.
        assert_eq!(rom_regression_cases().len(), 13);
    }

    #[test]
    fn rom_table_names_match_cxx() {
        let names: Vec<&str> = rom_regression_cases().iter().map(|c| c.name.as_str()).collect();
        assert_eq!(
            names,
            vec![
                "nrom", "mmc1", "uxrom", "cnrom", "mmc3", "mmc5",
                "axrom", "colordreams", "gnrom", "vrc2and4", "vrc6",
                "vrc7", "nestest",
            ]
        );
    }

    #[test]
    fn frame_buf_size_matches_cxx() {
        assert_eq!(FRAME_BUF_SIZE, 256 * 240);
        assert_eq!(FRAMES_TO_RUN, 60);
    }

    // ---------------- Path resolution ------------------------------------

    #[test]
    fn resolve_relative_path_against_workdir() {
        let p = resolve_rom_path(Path::new("/tmp/work"), "fixtures/x.nes");
        assert_eq!(p, PathBuf::from("/tmp/work/fixtures/x.nes"));
    }

    #[test]
    fn resolve_absolute_path_passes_through() {
        let p = resolve_rom_path(Path::new("/tmp/work"), "/abs/x.nes");
        assert_eq!(p, PathBuf::from("/abs/x.nes"));
    }
}
