use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let cbindgen = find_cbindgen();
    let config = format!("{}/cbindgen.toml", crate_dir);

    // Generate utils header
    let utils_out = format!("{}/target/fceux11_rust_utils.h", crate_dir);
    let status = Command::new(&cbindgen)
        .args(&["--crate", "fceux11-utils", "--config", &config, "--output", &utils_out])
        .current_dir(&crate_dir)
        .status()
        .expect("Failed to run cbindgen for utils");
    assert!(status.success(), "cbindgen for utils failed");

    // Generate media header
    let media_out = format!("{}/target/fceux11_rust_media.h", crate_dir);
    let status = Command::new(&cbindgen)
        .args(&["--crate", "fceux11-media", "--config", &config, "--output", &media_out])
        .current_dir(&crate_dir)
        .status()
        .expect("Failed to run cbindgen for media");
    assert!(status.success(), "cbindgen for media failed");

    // Generate formats header
    let formats_out = format!("{}/target/fceux11_rust_formats.h", crate_dir);
    let status = Command::new(&cbindgen)
        .args(&["--crate", "fceux11-formats", "--config", &config, "--output", &formats_out])
        .current_dir(&crate_dir)
        .status()
        .expect("Failed to run cbindgen for formats");
    assert!(status.success(), "cbindgen for formats failed");

    // Merge into final header
    merge_headers(&crate_dir, &utils_out, &media_out, &formats_out);

    // Tell cargo to rerun if sources change
    println!("cargo:rerun-if-changed=cbindgen.toml");
    println!("cargo:rerun-if-changed=crates/fceux11-utils/src");
    println!("cargo:rerun-if-changed=crates/fceux11-media/src");
    println!("cargo:rerun-if-changed=crates/fceux11-formats/src");
}

fn find_cbindgen() -> String {
    // Try CARGO directory first
    if let Ok(cargo) = env::var("CARGO") {
        let cargo_path = Path::new(&cargo);
        if let Some(bin_dir) = cargo_path.parent() {
            let candidate = bin_dir.join("cbindgen.exe");
            if candidate.exists() {
                return candidate.to_string_lossy().to_string();
            }
        }
    }
    // Fallback: try PATH
    if let Ok(path_var) = env::var("PATH") {
        for dir in path_var.split(';') {
            let candidate = Path::new(dir).join("cbindgen.exe");
            if candidate.exists() {
                return candidate.to_string_lossy().to_string();
            }
        }
    }
    panic!("cbindgen.exe not found. Install with: cargo install cbindgen");
}

fn merge_headers(crate_dir: &str, utils_path: &str, media_path: &str, formats_path: &str) {
    let mut output = String::new();
    output.push_str("/* Auto-generated by cbindgen. Do not edit. */\n\n");
    output.push_str("#ifndef FCEUX11_RUST_H\n");
    output.push_str("#define FCEUX11_RUST_H\n\n");
    output.push_str("#include <stdbool.h>\n");
    output.push_str("#include <stdint.h>\n\n");
    output.push_str("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");
    output.push_str("/* === v0.2.13 Slice types (manually appended) === */\n");
    output.push_str("typedef struct FceuSlice {\n");
    output.push_str("  const uint8_t *ptr;\n");
    output.push_str("  size_t len;\n");
    output.push_str("} FceuSlice;\n\n");
    output.push_str("typedef struct FceuSliceMut {\n");
    output.push_str("  uint8_t *ptr;\n");
    output.push_str("  size_t len;\n");
    output.push_str("} FceuSliceMut;\n\n");

    let utils_body = extract_body(&fs::read_to_string(utils_path).unwrap());
    let media_body = extract_body(&fs::read_to_string(media_path).unwrap());
    let formats_body = extract_body(&fs::read_to_string(formats_path).unwrap());

    output.push_str(&utils_body);
    if !utils_body.is_empty() && !media_body.is_empty() {
        output.push('\n');
    }
    output.push_str(&media_body);
    if !media_body.is_empty() && !formats_body.is_empty() {
        output.push('\n');
    }
    output.push_str(&formats_body);

    output.push_str("\n#ifdef __cplusplus\n}\n#endif\n\n");
    output.push_str("#endif /* FCEUX11_RUST_H */\n");

    fs::write(format!("{}/fceux11_rust.h", crate_dir), output)
        .expect("Failed to write merged header");
}

fn extract_body(content: &str) -> String {
    let mut result = String::new();

    for line in content.lines() {
        let trimmed = line.trim();

        // Skip includes (we provide our own)
        if trimmed.starts_with("#include") {
            continue;
        }

        // Skip cbindgen header/version comments (we provide our own)
        if trimmed == "/* Auto-generated by cbindgen. Do not edit. */"
            || trimmed.starts_with("/* Generated with cbindgen:")
        {
            continue;
        }

        // Skip header guard directives
        if trimmed.starts_with("#ifndef")
            || trimmed.starts_with("#define")
            || trimmed.starts_with("#endif")
        {
            continue;
        }

        // Empty lines at the start
        if result.is_empty() && trimmed.is_empty() {
            continue;
        }

        result.push_str(line);
        result.push('\n');
    }

    result.trim_end().to_string()
}
