[workspace]
members = [".", "crates/*", "tests/*"]
resolver = "3"

[workspace.package]
version = "0.2.19"
edition = "2024"

[profile.release]
panic = "abort"
lto = true

[package]
name = "fceux11-rust"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["staticlib"]
name = "fceux11_rust"

[dependencies]
fceux11-utils = { path = "crates/fceux11-utils" }
fceux11-media = { path = "crates/fceux11-media" }
fceux11-formats = { path = "crates/fceux11-formats" }

[build-dependencies]
cbindgen = "0.29.3"
