/* Auto-generated by cbindgen. Do not edit. */

#ifndef FCEUX11_RUST_H
#define FCEUX11_RUST_H

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* === v0.2.13 Slice types (manually appended) === */
typedef struct FceuSlice {
  const uint8_t *ptr;
  size_t len;
} FceuSlice;

typedef struct FceuSliceMut {
  uint8_t *ptr;
  size_t len;
} FceuSliceMut;

/**
 * Rust implementation of Unicode UTF conversion routines.
 * Replaces src/utils/ConvertUTF.c with a memory-safe equivalent.
 *
 * Phase 6 (v0.2.7): Unicode Conversion
 */
typedef enum ConversionResult {
  ConversionOK = 0,
  SourceExhausted = 1,
  TargetExhausted = 2,
  SourceIllegal = 3,
} ConversionResult;

typedef enum ConversionFlags {
  StrictConversion = 0,
  LenientConversion = 1,
} ConversionFlags;

typedef struct FceuGuid {
  uint8_t data[16];
} FceuGuid;

/**
 * C-compatible MD5 context layout. Must match `struct md5_context` in C++ exactly.
 */
typedef struct md5_context {
  uint32_t total[2];
  uint32_t state[4];
  uint8_t buffer[64];
} md5_context;

/**
 * C ABI: Convert UTF-8 to UTF-16.
 *
 * # Safety
 * All pointer parameters must be valid and non-null (except as noted).
 */
enum ConversionResult fceux11_rust_convert_utf8_to_utf16(const uint8_t **source_start,
                                                         const uint8_t *source_end,
                                                         uint16_t **target_start,
                                                         const uint16_t *target_end,
                                                         enum ConversionFlags flags);

/**
 * C ABI: Convert UTF-16 to UTF-8.
 *
 * # Safety
 * All pointer parameters must be valid and non-null.
 */
enum ConversionResult fceux11_rust_convert_utf16_to_utf8(const uint16_t **source_start,
                                                         const uint16_t *source_end,
                                                         uint8_t **target_start,
                                                         const uint8_t *target_end,
                                                         enum ConversionFlags flags);

/**
 * C ABI: Convert UTF-8 to UTF-32.
 *
 * # Safety
 * All pointer parameters must be valid and non-null.
 */
enum ConversionResult fceux11_rust_convert_utf8_to_utf32(const uint8_t **source_start,
                                                         const uint8_t *source_end,
                                                         uint32_t **target_start,
                                                         const uint32_t *target_end,
                                                         enum ConversionFlags flags);

/**
 * C ABI: Convert UTF-32 to UTF-8.
 *
 * # Safety
 * All pointer parameters must be valid and non-null.
 */
enum ConversionResult fceux11_rust_convert_utf32_to_utf8(const uint32_t **source_start,
                                                         const uint32_t *source_end,
                                                         uint8_t **target_start,
                                                         const uint8_t *target_end,
                                                         enum ConversionFlags flags);

/**
 * C ABI: Convert UTF-16 to UTF-32.
 *
 * # Safety
 * All pointer parameters must be valid and non-null.
 */
enum ConversionResult fceux11_rust_convert_utf16_to_utf32(const uint16_t **source_start,
                                                          const uint16_t *source_end,
                                                          uint32_t **target_start,
                                                          const uint32_t *target_end,
                                                          enum ConversionFlags flags);

/**
 * C ABI: Convert UTF-32 to UTF-16.
 *
 * # Safety
 * All pointer parameters must be valid and non-null.
 */
enum ConversionResult fceux11_rust_convert_utf32_to_utf16(const uint32_t **source_start,
                                                          const uint32_t *source_end,
                                                          uint16_t **target_start,
                                                          const uint16_t *target_end,
                                                          enum ConversionFlags flags);

/**
 * C ABI: Check whether a byte sequence is a legal UTF-8 sequence.
 *
 * # Safety
 * `source` and `source_end` must be valid pointers with `source <= source_end`.
 */
uint8_t fceux11_rust_is_legal_utf8_sequence(const uint8_t *source, const uint8_t *source_end);

/**
 * C ABI: Compute CRC32 over a byte buffer with an optional initial CRC value.
 *
 * # Safety
 * `buf` must point to at least `len` valid bytes, or be NULL when `len` is 0.
 */
uint32_t fceux11_rust_crc32(uint32_t crc, const uint8_t *buf, uint32_t len);

/**
 * C ABI: Return the next power of two for `n`.
 * If `n` is already a power of two, returns `n`.
 * For `n == 0`, returns `0` to match original C++ behavior.
 */
uint32_t fceux11_rust_uppow2(uint32_t n);

/**
 * C ABI: Generate a new random GUID (UUID v4) into the provided buffer.
 *
 * # Safety
 * `guid` must point to a valid, writable `FceuGuid`.
 */
void fceux11_rust_guid_new(struct FceuGuid *guid);

/**
 * C ABI: Convert a GUID to a hex string representation.
 *
 * # Safety
 * `guid` must point to a valid 16-byte GUID.
 * Returns a pointer to a thread-local static buffer. Caller should copy immediately.
 */
const char *fceux11_rust_guid_to_string(const struct FceuGuid *guid);

/**
 * C ABI: Parse a hex string into a GUID.
 *
 * # Safety
 * `guid` must point to a valid, writable `FceuGuid`.
 * `str` must point to a null-terminated string in the format "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX".
 */
void fceux11_rust_guid_scan(struct FceuGuid *guid,
                            const char *str);

/**
 * # Safety
 * `ctx` must point to a valid, writable `Md5Context`.
 */
void fceux11_rust_md5_starts(struct md5_context *ctx);

/**
 * # Safety
 * `ctx` must point to a valid, writable `Md5Context`.
 * `input` must point to at least `length` valid bytes, or be NULL when `length` is 0.
 */
void fceux11_rust_md5_update(struct md5_context *ctx, const uint8_t *input, uint32_t length);

/**
 * # Safety
 * `ctx` must point to a valid, writable `Md5Context`.
 * `digest` must point to at least 16 writable bytes.
 */
void fceux11_rust_md5_finish(struct md5_context *ctx, uint8_t *digest);

/**
 * # Safety
 * `md5` must point to a valid 16-byte MD5 digest.
 * Returns a pointer to a thread-local static buffer. Caller should copy immediately.
 */
const char *fceux11_rust_md5_asciistr(const uint8_t *md5);

/**
 * C ABI: Create a single directory.
 *
 * Returns 0 on success, -1 on failure.
 *
 * # Safety
 * `path` must be a valid null-terminated UTF-8 string.
 */
int32_t fceux11_rust_mkdir(const char *path);

/**
 * C ABI: Create a directory and all its parents.
 *
 * Returns 0 on success, -1 on failure.
 *
 * # Safety
 * `path` must be a valid null-terminated UTF-8 string.
 */
int32_t fceux11_rust_mkpath(const char *path);

/**
 * C ABI: Check whether a regular file exists.
 *
 * Returns 1 if the path exists and is a file, 0 otherwise.
 *
 * # Safety
 * `filepath` must be a valid null-terminated UTF-8 string.
 */
int32_t fceux11_rust_file_exists(const char *filepath);

/**
 * C ABI: Sleep for `ms` milliseconds.
 *
 * Returns 0.
 */
int32_t fceux11_rust_msleep(int32_t ms);

/**
 * C ABI: Create a new `ProfilerFuncMap` and return an opaque handle.
 */
void *fceux11_rust_profiler_map_create(void);

/**
 * C ABI: Destroy a `ProfilerFuncMap` handle.
 */
void fceux11_rust_profiler_map_destroy(void *handle);

/**
 * C ABI: Register a `funcProfileRecord*` under the key `file:line`.
 */
int fceux11_rust_profiler_map_add_record(void *handle,
                                         const char *file,
                                         int line,
                                         const char *_func,
                                         const char *_comment,
                                         void *rec);

/**
 * C ABI: Push a record pointer onto the call stack.
 */
void fceux11_rust_profiler_map_push_stack(void *handle, void *rec);

/**
 * C ABI: Pop the top of the call stack.
 */
void fceux11_rust_profiler_map_pop_stack(void *handle, void *_rec);

/**
 * C ABI: Begin iteration over the map. Returns the first record, or null.
 */
void *fceux11_rust_profiler_map_iterate_begin(void *handle);

/**
 * C ABI: Advance iteration and return the next record, or null.
 */
void *fceux11_rust_profiler_map_iterate_next(void *handle);

/**
 * C ABI: Add a C++ `profilerFuncMap*` to the global thread list.
 */
int fceux11_rust_profiler_mgr_add(void *cpp_ptr);

/**
 * C ABI: Remove a C++ `profilerFuncMap*` from the global thread list.
 *
 * `should_destroy` is ignored; destruction is handled by C++.
 */
int fceux11_rust_profiler_mgr_remove(void *cpp_ptr, int _should_destroy);

/**
 * C ABI: Clear the global thread list (called from `profilerManager` destructor).
 */
void fceux11_rust_profiler_mgr_clear(void);

/**
 * C ABI: Return the current monotonic timestamp in nanoseconds.
 *
 * The returned value is relative to an arbitrary epoch established
 * at program startup (or first call). It is guaranteed to be
 * monotonically increasing and suitable for high-precision delta
 * measurements.
 */
uint64_t fceux11_rust_timestamp_now(void);

/**
 * C ABI: Return the timestamp frequency in Hz.
 *
 * The Rust implementation uses nanosecond resolution, so the
 * frequency is always 1_000_000_000 Hz.
 */
uint64_t fceux11_rust_timestamp_freq(void);

/**
 * C ABI: Initialize the timestamp module.
 *
 * Ensures the base instant is captured. Returns 1 on success.
 */
int32_t fceux11_rust_timestamp_init(void);
/**
 * Number of glyphs encoded in `FONT6X7` (chars 0x20..=0x7A = 91 printable,
 * but original C++ uses 99 to allow safe over-read for out-of-range chars).
 */



/**
 * Filter byte prepended to each scanline: 0 = "None" (no filtering),
 * matching `src/video.cpp:578` and `:677`.
 */

/**
 * `XBuf` is always 256×256 (65536 bytes), but only the
 * `[first_sline, last_sline]` rows are emitted to disk.
 */



/**
 * NES palette: 64 colors × 3 channels = 192 bytes for `GetScreenPixel`'s
 * caller-supplied PLTE-like buffer, OR 256 entries × 3 = 768 bytes for
 * the indexed snapshot's PLTE chunk (always 256 entries per `src/video.cpp:660`).
 */




/**
 * C-visible opaque type for audio filter state.
 */
typedef struct FceuFilterState {
  uint8_t _private[0];
} FceuFilterState;

typedef struct Pal {
  uint8_t r;
  uint8_t g;
  uint8_t b;
} Pal;

/**
 * Encode-time arguments shared by the RGB and indexed snapshot paths.
 *
 * The caller owns all pointers. All lengths are validated against the
 * required minimums in the encoder functions. The output buffer
 * (`out.ptr`, `out.len`) must be at least 256 KiB to hold the worst-case
 * PNG (240 scanlines × 768 RGB + 12 byte scanline header + zlib overhead
 * + chunk headers).
 */
typedef struct FceuVideoEncodeArgs {
  /**
   * 256×256 indexed pixel buffer (NES palette indices in the low 6
   * bits, with deemph/overlay bits in the high bits).
   */
  const uint8_t *xbuf;
  /**
   * Must equal `FCEUX11_RUST_VIDEO_XBUF_SIZE`.
   */
  uintptr_t xbuf_len;
  /**
   * Inclusive first scanline index, 0..=255. Validated.
   */
  int32_t first_sline;
  /**
   * Inclusive last scanline index, must satisfy `first_sline <= last_sline <= 255`.
   */
  int32_t last_sline;
  /**
   * Caller-allocated output buffer.
   */
  FceuSliceMut out;
} FceuVideoEncodeArgs;

/**
 * Apply a 14-row dimmed background to a 256-wide pixel buffer.
 *
 * The C++ version writes `(dest[y*256+x] & 0x0F) | 0xC0` for `x` in
 * `[offs, 256-offs)`, where `offs` comes from a symmetric `otable` lookup.
 * Each row is at `y*256`, so `len` must be `>= 14 * 256 = 3584` bytes.
 *
 * `dest` may be null (no-op). Returns silently if `len` is too small.
 */
void fceux11_rust_drawing_draw_text_line_bg(uint8_t *dest, uintptr_t dest_len);

/**
 * Rasterize a NUL-terminated text string into `dest` using the 6×7 font.
 *
 * Equivalent to the C++ `DrawTextTrans` + `DrawTextTransWH` combo.
 * `width` is the row stride in pixels (must be 256 for XBuf-style buffers).
 * `fgcolor` is the foreground palette index. `max_w`/`max_h` clip the
 * output rectangle; `border` (0/1/2) controls the soft shadow / outline
 * weight (matching the original C++ behavior, including the historical
 * `y<15` clamp bug preserved for bytewise equivalence).
 */
void fceux11_rust_drawing_draw_text_trans(uint8_t *dest,
                                          uintptr_t dest_len,
                                          const char *textmsg,
                                          uint32_t width,
                                          uint8_t fgcolor,
                                          int max_w,
                                          int max_h,
                                          int border);

/**
 * Draw the 10-digit save-state status row into the pixel buffer.
 *
 * `xbaf` is the base pointer (already offset to `(LastSLine - 34) * 256 - 4`
 * from `XBuf`, computed by the C++ wrapper). `nstatus[0..10]` flags which
 * digits are active. `cur` highlights one of the 10 cells (border color 4).
 *
 * The C++ layout has a 21-byte tile overlap quirk that is preserved verbatim
 * (see `SSTAT` doc comment).
 */
void fceux11_rust_drawing_draw_number_row(uint8_t *xbaf,
                                          uintptr_t xbaf_len,
                                          const int *nstatus,
                                          int cur);

/**
 * Draw a status icon (play/record/pause/none) into the pixel buffer.
 *
 * `base` is the destination pointer (already offset to
 * `(LastSLine - y) * 256 + 495 + x_offset` from the XBuf base, computed by
 * the C++ wrapper). `base_len` is the remaining byte count from `base` to
 * the end of XBuf — the worst-case write is `(14*256 + 14) = 3598` bytes
 * below `base`, so we require at least that.
 *
 * `icon_kind`: 0 = none, 1 = play, 2 = record, 3 = pause. Each icon is
 * drawn with a black inner pass and a color-4 outer pass (matching the
 * C++ `drawstatus` two-pass shadow effect).
 */
void fceux11_rust_drawing_draw_status_icon(uint8_t *base, uintptr_t base_len, uint8_t icon_kind);

/**
 * Return the width (in pixels) of an ASCII character, or 0 for the spacebar.
 */
uint8_t fceux11_rust_drawing_font_width(uint8_t ch);

/**
 * C ABI: Create a new filter state and return an opaque handle.
 */
struct FceuFilterState *fceux11_rust_filter_state_create(void);

/**
 * C ABI: Destroy a filter state handle.
 */
void fceux11_rust_filter_state_destroy(struct FceuFilterState *handle);

/**
 * C ABI: Initialise FIR coefficients and resampling state.
 *
 * `ntsc_cpu` and `pal_cpu` are the base CPU clock frequencies in Hz
 * (e.g. 1789772.727… for NTSC, 1662607.125 for PAL).
 */
void fceux11_rust_filter_make(struct FceuFilterState *handle,
                              int32_t rate,
                              int32_t soundq,
                              int32_t is_pal,
                              double ntsc_cpu,
                              double pal_cpu);

/**
 * C ABI: `SexyFilter` wrapper.
 *
 * `in_buf` and `out_buf` may point to the same memory.
 */
void fceux11_rust_filter_sexy(struct FceuFilterState *handle,
                              int32_t *in_buf,
                              int32_t *out_buf,
                              int32_t count,
                              int32_t snd_rate,
                              int32_t sound_volume,
                              int32_t soundq);

/**
 * C ABI: `SexyFilter2` wrapper.
 */
void fceux11_rust_filter_sexy2(struct FceuFilterState *handle, int32_t *buf, int32_t count);

/**
 * C ABI: `NeoFilterSound` wrapper.
 *
 * Returns the number of samples written to `out`.
 * `leftover` is set to the number of samples that must be copied from the
 * end of `in` to the beginning of `in` on the next call.
 */
int32_t fceux11_rust_filter_neo(struct FceuFilterState *handle,
                                int32_t *in_buf,
                                int32_t *out_buf,
                                uint32_t inlen,
                                int32_t *leftover,
                                int32_t soundq,
                                int32_t lowpass,
                                void (*neo_fill)(int32_t*, int32_t),
                                int32_t snd_rate,
                                int32_t sound_volume);

/**
 * Compute the 64-entry NTSC base palette from tint and hue.
 * `out` must point to at least 64 `Pal` entries.
 */
void fceux11_rust_palette_calc_ntsc(int tint, int hue, struct Pal *out);

/**
 * Expand a 64-entry base palette into 512 entries with de-emphasis applied.
 * `src` must point to 64 `Pal` entries.
 * `dst` must point to 512 `Pal` entries.
 * It is safe for `src == dst` (in-place expansion).
 */
void fceux11_rust_palette_apply_deemphasis(const struct Pal *src, struct Pal *dst);

/**
 * Convert a 512-entry palette to grayscale.
 * `src` and `dst` must each point to 512 `Pal` entries.
 */
void fceux11_rust_palette_make_grayscale(const struct Pal *src, struct Pal *dst);

/**
 * Draw the NTSC tint/hue control bars into a pixel buffer.
 * `xbuf` must be a non-null pointer to an 8-bit indexed pixel buffer.
 * `width` is the horizontal stride (typically 256).
 * `which` is the bar length in pixels (typically ntschue*2 or ntsctint*2).
 */
void fceux11_rust_palette_draw_control_bars(uint8_t *xbuf, int width, int which);

/**
 * Encode an RGB snapshot PNG to the caller's output buffer.
 *
 * `args` carries the indexed XBuf, scanline range, and pre-allocated
 * output buffer. `rgb_scanlines` is a `width * 3 * totallines`-byte
 * buffer of pre-computed RGB triples (the C++ side runs
 * `ModernDeemphColorMap` per pixel and packs them contiguously).
 *
 * # Returns
 *
 * Number of bytes written to `args.out` on success, or `0` on:
 * - null `args` / null `xbuf` / null `out.ptr`
 * - `args.xbuf_len < 65536`
 * - `rgb_scanlines.len() < 256 * 3 * totallines`
 * - `args.out.len < bytes_needed`
 * - `first_sline`/`last_sline` out of `[0, 256)`
 *
 * # Safety
 *
 * All pointers in `args` and `rgb_scanlines` must be valid for the
 * declared lengths. The caller may read from `args.xbuf` and
 * `rgb_scanlines`; the caller may write to `args.out.ptr..out.ptr+out.len`.
 */
uintptr_t fceux11_rust_video_encode_png_rgb(const struct FceuVideoEncodeArgs *args,
                                            FceuSlice rgb_scanlines);

/**
 * Encode an indexed (palette) snapshot PNG to the caller's output
 * buffer.
 *
 * `args` carries the indexed XBuf, scanline range, and pre-allocated
 * output buffer. `plte_rgb` is a 768-byte (256 entries × 3 channels)
 * palette — one RGB triple per NES palette index.
 *
 * # Returns
 *
 * Number of bytes written to `args.out` on success, or `0` on:
 * - null `args` / null `xbuf` / null `out.ptr`
 * - `args.xbuf_len < 65536`
 * - `plte_rgb.len() < 768`
 * - `args.out.len < bytes_needed`
 * - `first_sline`/`last_sline` out of `[0, 256)`
 *
 * # Safety
 *
 * Same as `fceux11_rust_video_encode_png_rgb`.
 */
uintptr_t fceux11_rust_video_encode_png_indexed(const struct FceuVideoEncodeArgs *args,
                                                FceuSlice plte_rgb);

/**
 * Read a single screen pixel and return its 24-bit RGB value.
 *
 * Mirrors `src/video.cpp:489-503`'s `GetScreenPixel`. The caller
 * supplies a 192-byte (64×3) NES palette; indexed pixel `p` is mapped
 * to `palette[((p & 0x3F) * 3)..((p & 0x3F) * 3 + 3)]`.
 *
 * If `usebackup != 0`, reads from `xbackbuf` instead of `xbuf`.
 *
 * # Returns
 *
 * - `-1` on out-of-bounds (`x`/`y` not in `[0, 256)`).
 * - `0` on success; the 24-bit RGB value is written to `rgb_out` (which
 *   must be at least 3 bytes long).
 *
 * # Safety
 *
 * `xbuf`, `xbackbuf`, and `rgb_out` must be non-null and point to at
 * least `xbuf_len` / `xbackbuf_len` / 3 readable/writable bytes
 * respectively.
 */
int32_t fceux11_rust_video_get_screen_pixel(int32_t x,
                                            int32_t y,
                                            bool usebackup,
                                            FceuSlice xbuf,
                                            FceuSlice xbackbuf,
                                            FceuSlice palette_64,
                                            FceuSliceMut rgb_out);

/**
 * Read a single screen pixel's palette index (low 6 bits).
 *
 * Mirrors `src/video.cpp:505-515`'s `GetScreenPixelPalette`.
 *
 * # Returns
 *
 * - `-1` on out-of-bounds.
 * - Otherwise, the palette index in the low 6 bits (`0..=63`).
 *
 * # Safety
 *
 * `xbuf` and `xbackbuf` must be non-null and point to at least
 * `xbuf_len` / `xbackbuf_len` readable bytes.
 */
int32_t fceux11_rust_video_get_screen_pixel_palette(int32_t x,
                                                    int32_t y,
                                                    bool usebackup,
                                                    FceuSlice xbuf,
                                                    FceuSlice xbackbuf);

/**
 * Set the "save snapshot as" filename. The C++ side calls this from
 * `FCEUI_SetSnapshotAsName`. Passing a null pointer or `name_len == 0`
 * clears the name.
 *
 * # Safety
 *
 * If `name` is non-null, it must point to at least `name_len` valid
 * UTF-8 bytes. The bytes need not be NUL-terminated.
 */
void fceux11_rust_video_set_snapshot_as_name(const char *name, uintptr_t name_len);

/**
 * Read the "save snapshot as" filename into the caller's buffer.
 *
 * # Returns
 *
 * Number of bytes copied (excluding any NUL terminator). Returns `0` if:
 * - no name is set,
 * - `buf` is null,
 * - the name is too long for `buf_len` (in which case the name is
 *   **truncated** to fit and `buf_len - 1` is returned).
 *
 * # Safety
 *
 * `buf` must point to at least `buf_len` writable bytes (or be null
 * when `buf_len == 0`).
 */
uintptr_t fceux11_rust_video_get_snapshot_as_name(char *buf, uintptr_t buf_len);

/**
 * C ABI: Begin recording a wave file.
 *
 * Opens (or truncates) `path` and writes a 44-byte PCM WAV header.
 * `sample_rate` is passed explicitly from C++ to avoid reading global state.
 *
 * # Safety
 * `path` must be a valid null-terminated UTF-8 string.
 */
bool fceux11_rust_wave_begin(const char *path, uint32_t sample_rate);

/**
 * C ABI: Returns whether a wave recording is currently active.
 */
bool fceux11_rust_wave_running(void);

/**
 * C ABI: Write audio samples to the active wave file.
 *
 * `buffer` points to `count` little-endian signed 16-bit samples.
 * Returns the number of bytes written, or 0 if no file is open.
 *
 * # Safety
 * `buffer` must point to at least `count` valid `i16` samples, or be NULL when `count` is 0.
 */
int64_t fceux11_rust_wave_write(const int16_t *buffer, int32_t count);

/**
 * C ABI: Finalize and close the active wave file.
 *
 * Seeks back to the header and updates the RIFF chunk size and data chunk size.
 * Returns 1 on success, 0 if no file was open.
 */
int32_t fceux11_rust_wave_end(void);
/**
 * One FDS disk side is exactly 65500 bytes of payload.
 */

/**
 * FDS BIOS image size in bytes.
 */

/**
 * FDS work RAM size, mapped at $6000–$DFFF.
 */

/**
 * FDS CHR RAM size, mapped at $0000–$1FFF.
 */

/**
 * Maximum number of disk sides supported per image.
 */

/**
 * CPU cycles between motor-on/seek events and the disk-seek IRQ.
 */

/**
 * Sentinel `InDisk` value meaning "no disk inserted".
 */

/**
 * IRQa bit 0: when set, IRQ rearms on each fire.
 */

/**
 * IRQa bit 1: master IRQ enable.
 */

/**
 * Block-FSM: initial / no-block state.
 */

/**
 * Block-FSM: disk volume label block (0x38 bytes).
 */

/**
 * Block-FSM: file-count block (0x02 bytes).
 */

/**
 * Block-FSM: file header block (0x10 bytes).
 */

/**
 * Block-FSM: file data block (0x01 + file_size bytes).
 */

/**
 * IRQ source bit for the FDS timer IRQ (mirrors C++ `FCEU_IQEXT`).
 */

/**
 * IRQ source bit for the FDS disk-seek IRQ (mirrors C++ `FCEU_IQEXT2`).
 */


















































/**
 * In-memory file buffer. Corresponds to C++ `EMUFILE_MEMORY`.
 */
typedef struct EmuFileMem EmuFileMem;

typedef struct FceuMovieData FceuMovieData;

typedef struct FceuInesHeader {
  uint8_t id[4];
  uint8_t rom_size;
  uint8_t vrom_size;
  uint8_t rom_type;
  uint8_t rom_type2;
  uint8_t rom_type3;
  uint8_t upper_rom_vrom_size;
  uint8_t ram_size;
  uint8_t vram_size;
  uint8_t tv_system;
  uint8_t vs_hardware;
  uint8_t misc_roms;
  uint8_t expansion;
} FceuInesHeader;

typedef struct FceuRomSizes {
  /**
   * Number of 16 KiB PRG banks (power of two; 256 for the special
   * iNES-1 zero-size case).
   */
  uint32_t rom_size_16kb;
  /**
   * Number of 8 KiB CHR banks (power of two or iNES-2 computed).
   */
  uint32_t vrom_size_8kb;
  /**
   * CHR-RAM size in bytes.  -1 means "not applicable" (CHR-ROM
   * present).  0 means "determined later".
   */
  int32_t chrram_size;
  /**
   * Raw (not-rounded) PRG size in 16 KiB units, before .
   * Needed for non-power-of-2 ROM loading and debug printing.
   */
  uint32_t rom_size_raw;
} FceuRomSizes;

typedef struct FceuSaveGameEntry {
  uint8_t *bufptr;
  uint32_t buflen;
} FceuSaveGameEntry;

/**
 * Opaque handle for an in-memory file.
 */
typedef struct EmuFileMem *EmuFileMemHandle;

/**
 * Result of header recognition on a 16-byte prefix.
 *
 * `kind`:
 * - `0` = unrecognized format (caller should return LOADER_INVALID_FORMAT)
 * - `1` = standard `FDS\x1a` header at offset 0 (16-byte header before
 *   the first side's payload)
 * - `2` = raw image with `*NINTENDO-HVC*` marker at offset 1 (no header
 *   to skip; sides are derived from file size)
 */
typedef struct FceuFdsHeaderInfo {
  uint8_t kind;
  /**
   * Bytes to skip before the first side's payload (16 for kind=1,
   * 0 for kind=2, 0 for kind=0).
   */
  uint8_t header_size;
  /**
   * For kind=1, the side count advertised by header[4].
   * For kind=0/2, set to 0.
   */
  uint8_t advertised_sides;
} FceuFdsHeaderInfo;

/**
 * Decision returned by `fceux11_rust_fds_irq_tick`.
 * C++ acts on these by calling `X6502_IRQBegin(FCEU_IQEXT)` and
 * `X6502_IRQBegin(FCEU_IQEXT2)` respectively.
 */
typedef struct FceuFdsIrqTickResult {
  bool timer_fire;
  bool seek_fire;
} FceuFdsIrqTickResult;

/**
 * Mirror of the C++ IRQ-related globals used by `FDSFix`.
 * `irq_count` and `disk_seek_irq` may go negative after subtraction
 * (the C++ comparison is `<= 0`).
 */
typedef struct FceuFdsIrqState {
  int32_t irq_count;
  int32_t irq_latch;
  uint8_t irq_a;
  int32_t disk_seek_irq;
  uint8_t fds_regs_5;
} FceuFdsIrqState;

/**
 * State delta to apply after a $4025 write.
 * `new_block`/`new_blocklen` are meaningful only when `motor_on_edge`
 * is true. If `transfer_reset` is set, C++ overrides the block to
 * `DSK_INIT` and zeros `blockstart`/`blocklen`/`diskaddr` itself.
 */
typedef struct FceuFdsWrite4025Result {
  bool motor_on_edge;
  bool transfer_reset;
  bool motor_on;
  uint8_t new_block;
  uint16_t new_blocklen;
} FceuFdsWrite4025Result;

typedef struct FceuInesHInfoResult {
  int32_t mapper;
  int32_t mapper_mask;
  int32_t mirror;
  int32_t force_battery;
  int32_t clear_vrom;
} FceuInesHInfoResult;

/**
 * C-compatible movie record layout.
 */
typedef struct FceuMovieRecord {
  uint8_t joysticks[4];
  uint8_t zapper_x[2];
  uint8_t zapper_y[2];
  uint8_t zapper_b[2];
  uint8_t zapper_bogo[2];
  uint64_t zapper_zaphit[2];
  uint8_t commands;
} FceuMovieRecord;

/**
 * C-compatible input descriptor for dumping a movie.
 * All pointer fields may be null / zero when unused.
 */
typedef struct FceuMovieDataInput {
  int32_t version;
  int32_t emu_version;
  int32_t fds;
  bool pal_flag;
  bool ppu_flag;
  uint8_t rom_checksum[16];
  const char *rom_filename;
  const uint8_t *savestate;
  uintptr_t savestate_len;
  const uint8_t *saveram;
  uintptr_t saveram_len;
  const struct FceuMovieRecord *records;
  uintptr_t records_count;
  const char *const *comments;
  uintptr_t comments_count;
  const char *const *subtitles;
  uintptr_t subtitles_count;
  int32_t rerecord_count;
  const char *guid;
  bool binary_flag;
  int32_t load_frame_count;
  int32_t ports[3];
  bool fourscore;
  bool microphone;
  int32_t ram_init_option;
  int32_t ram_init_seed;
} FceuMovieDataInput;

typedef struct FceuNsfHeader {
  uint8_t id[5];
  uint8_t version;
  uint8_t total_songs;
  uint8_t starting_song;
  uint8_t load_address_low;
  uint8_t load_address_high;
  uint8_t init_address_low;
  uint8_t init_address_high;
  uint8_t play_address_low;
  uint8_t play_address_high;
  uint8_t song_name[32];
  uint8_t artist[32];
  uint8_t copyright[32];
  uint8_t ntsc_speed[2];
  uint8_t bank_switch[8];
  uint8_t pal_speed[2];
  uint8_t video_system;
  uint8_t sound_chip;
  uint8_t expansion[4];
  uint8_t reserve[8];
} FceuNsfHeader;

typedef struct UnifBoardInfo {
  const char *name;
  int32_t flags;
} UnifBoardInfo;

typedef struct VsUniEntry {
  const char *name;
  uint64_t md5partial;
  int32_t mapper;
  uint8_t mirroring;
  uint8_t ppu;
  int32_t ioption;
  int32_t predip;
  uint8_t game_type;
} VsUniEntry;

/**
 * Compute `ROM_size` and `VROM_size` (in bank counts) from the iNES
 * header.  `mapper_no` is only used for the iNES-2 CHRRAM fallback.
 * Returns `true` on success.
 */
bool fceux11_rust_cart_compute_rom_sizes(const struct FceuInesHeader *header,
                                         bool is_nes2,
                                         struct FceuRomSizes *out);

/**
 * Return the default CHR-RAM size in bytes when no CHR-ROM is present.
 * For iNES-2 the caller should instead use `battery_vram_size +
 * vram_size`.  Returns -1 when CHR-ROM is present (`has_vrom` true).
 */
int32_t fceux11_rust_cart_compute_chrram_size(int32_t mapper_no,
                                              bool is_nes2,
                                              int32_t vram_size,
                                              int32_t battery_vram_size,
                                              bool has_vrom);

/**
 * Save battery-backed RAM to `path`.  Each non-null entry is written
 * sequentially.  Returns `true` on success.
 */
bool fceux11_rust_cart_battery_save(const char *path,
                                    const struct FceuSaveGameEntry *entries,
                                    uintptr_t count);

/**
 * Load battery-backed RAM from `path`.  Each non-null entry is read
 * sequentially.  Returns `true` on success (short reads are treated
 * as failure for that entry but the function still returns true if
 * the file could be opened; this matches the original C++ behaviour).
 */
bool fceux11_rust_cart_battery_load(const char *path,
                                    struct FceuSaveGameEntry *entries,
                                    uintptr_t count);

/**
 * Zero-fill all save-game buffers.  Does **not** invoke C++ reset
 * callbacks; the caller must handle those separately.
 */
void fceux11_rust_cart_battery_clear(const struct FceuSaveGameEntry *entries, uintptr_t count);

/**
 * Create a new in-memory EmuFile.
 */
EmuFileMemHandle fceux11_rust_emufile_mem_create(void);

/**
 * Create a new in-memory EmuFile with pre-allocated capacity.
 */
EmuFileMemHandle fceux11_rust_emufile_mem_create_with_capacity(uintptr_t capacity);

/**
 * Create a new in-memory EmuFile from raw bytes.
 */
EmuFileMemHandle fceux11_rust_emufile_mem_create_from_bytes(const uint8_t *ptr, uintptr_t len);

/**
 * Destroy an in-memory EmuFile handle.
 */
void fceux11_rust_emufile_mem_destroy(EmuFileMemHandle handle);

/**
 * Read bytes into C buffer. Returns bytes read.
 */
uintptr_t fceux11_rust_emufile_mem_fread(EmuFileMemHandle handle, uint8_t *ptr, uintptr_t bytes);

/**
 * Write bytes from C buffer. Returns bytes written.
 */
uintptr_t fceux11_rust_emufile_mem_fwrite(EmuFileMemHandle handle,
                                          const uint8_t *ptr,
                                          uintptr_t bytes);

/**
 * Seek within the memory file.
 * origin: 0 = SEEK_SET, 1 = SEEK_CUR, 2 = SEEK_END
 * Returns 0 on success, -1 on failure.
 */
int32_t fceux11_rust_emufile_mem_fseek(EmuFileMemHandle handle, int32_t offset, int32_t origin);

/**
 * Get current position.
 */
uint32_t fceux11_rust_emufile_mem_ftell(EmuFileMemHandle handle);

/**
 * Get size of memory buffer.
 */
uint32_t fceux11_rust_emufile_mem_size(EmuFileMemHandle handle);

/**
 * Truncate the memory buffer.
 */
void fceux11_rust_emufile_mem_truncate(EmuFileMemHandle handle, uint32_t length);

/**
 * Check fail bit (always false in Rust, kept for API parity).
 */
int32_t fceux11_rust_emufile_mem_fail(EmuFileMemHandle handle);

/**
 * Returns non-zero if at EOF.
 */
int32_t fceux11_rust_emufile_mem_eof(EmuFileMemHandle handle);

/**
 * Get read-only data pointer.
 */
const uint8_t *fceux11_rust_emufile_mem_data_ptr(EmuFileMemHandle handle);

/**
 * Ungetc: step position back by one.
 */
void fceux11_rust_emufile_mem_unget(EmuFileMemHandle handle);

/**
 * Read a u8 value.
 */
uint8_t fceux11_rust_emufile_mem_read8(EmuFileMemHandle handle);

/**
 * Write a u8 value.
 */
void fceux11_rust_emufile_mem_write8(EmuFileMemHandle handle, uint8_t val);

/**
 * Read a u16 LE.
 */
uint16_t fceux11_rust_emufile_mem_read16le(EmuFileMemHandle handle);

/**
 * Write a u16 LE.
 */
void fceux11_rust_emufile_mem_write16le(EmuFileMemHandle handle, uint16_t val);

/**
 * Read a u32 LE.
 */
uint32_t fceux11_rust_emufile_mem_read32le(EmuFileMemHandle handle);

/**
 * Write a u32 LE.
 */
void fceux11_rust_emufile_mem_write32le(EmuFileMemHandle handle, uint32_t val);

/**
 * Read a u64 LE.
 */
uint64_t fceux11_rust_emufile_mem_read64le(EmuFileMemHandle handle);

/**
 * Write a u64 LE.
 */
void fceux11_rust_emufile_mem_write64le(EmuFileMemHandle handle, uint64_t val);

/**
 * Recognize FDS disk-image format from a 16-byte prefix.
 *
 * `buf` must be non-null and point to at least 16 readable bytes.
 * `len` is the number of readable bytes available; a length below 16
 * (or below 15 for raw images) causes the function to return
 * `kind = 0`.
 *
 * Mirrors `src/fds.cpp:717–733`'s `memcmp` chain.
 */
struct FceuFdsHeaderInfo fceux11_rust_fds_validate_header(const uint8_t *buf, uintptr_t len);

/**
 * Clamp the side count to [1, FCEUX11_RUST_FDS_MAX_SIDES].
 *
 * If `has_fds_header != 0`, the `advertised` value is used as the
 * starting point (the byte at header[4]).  Otherwise the side count
 * is derived from `file_size / FCEUX11_RUST_FDS_DISK_SIDE_SIZE`,
 * matching the C++ "raw image" code path (`src/fds.cpp:719–723`).
 *
 * The strange `if (t < 65500) t = 65500;` line in the original is
 * preserved here: even a 0-byte raw image yields one side.
 */
uint8_t fceux11_rust_fds_compute_total_sides(uintptr_t file_size,
                                             uint8_t advertised,
                                             uint8_t has_fds_header);

/**
 * XOR the original disk image (`src`) into the current disk image
 * (`dst`) in place — `dst[i] ^= src[i]` for `i` in
 * `0..FCEUX11_RUST_FDS_DISK_SIDE_SIZE`.
 *
 * Used in three places to keep save-state binary identical regardless
 * of the run-time disk-write state:
 *   - `PreSave`  (src/fds.cpp:744)  — encode writes before serializing
 *   - `PostSave` (src/fds.cpp:753)  — undo encoding after serializing
 *   - `FDSStateRestore` (src/fds.cpp:118) — re-encode after load
 *
 * Both pointers must be non-null and point to at least
 * `FCEUX11_RUST_FDS_DISK_SIDE_SIZE` bytes.
 */
void fceux11_rust_fds_xor_disk_data(uint8_t *dst, const uint8_t *src);

/**
 * Decrement IRQ counters and report which IRQs should fire.
 *
 * 1:1 translation of `FDSFix` (src/fds.cpp:230–258).  Mutates the
 * caller's `state` in place so C++ can write the new values back to
 * its globals.  Returns `timer_fire`/`seek_fire` so C++ can issue
 * `X6502_IRQBegin(FCEU_IQEXT[2])` outside the FFI boundary.
 *
 * Puff Puff Golf notes (preserved verbatim from C++):
 * > Game freezes while music playing ingame after inserting Disk Side B.
 * > IRQ is usually fired at scanline 169 and 183 for music to work.
 * > At some point after inserting disk B, an IRQ is fired at scanline
 * > 174 which will just freeze game while music plays.
 * > If you ignore triggering IRQ altogether, game plays but no music.
 *
 * This is a historical behaviour of the original C++ — do NOT add a
 * suppression flag here.  The point of this migration is byte-for-byte
 * equivalence.
 *
 * `delta_cycles` is the number of CPU cycles elapsed since the
 * previous tick; the C++ caller (`MapIRQHook`) always passes a
 * non-negative value, but we use `wrapping_sub` for defensiveness.
 */
struct FceuFdsIrqTickResult fceux11_rust_fds_irq_tick(struct FceuFdsIrqState *state,
                                                      int32_t delta_cycles);

/**
 * Look up `mapperFDS_blocklen` for a given block type.
 * Returns 0 for unknown block types (including `DSK_INIT`).
 *
 * Mirrors the switch in `FDSWrite` case 0x4025 (src/fds.cpp:665–678).
 */
int32_t fceux11_rust_fds_block_size(uint8_t block_type, uint16_t file_size);

/**
 * Advance the block FSM on a motor-on edge.
 * 0→1, 1→2, 2→3, 3→4, 4→3, (>=5)→3 (FILEHDR clamp).
 */
uint8_t fceux11_rust_fds_block_advance_on_motor(uint8_t current_block);

/**
 * Compute the value returned by reading $4030.
 * Mirrors `FDSRead4030` (src/fds.cpp:261–265) — the C++ wrapper
 * retains the `fceuindbg`-guarded `X6502_IRQEnd` calls.
 */
uint8_t fceux11_rust_fds_read_4030_value(bool irq_low_ext, bool irq_low_ext2);

/**
 * Compute the value returned by reading $4032.
 * Mirrors `FDSRead4032` (src/fds.cpp:314–324).
 */
uint8_t fceux11_rust_fds_read_4032_value(uint8_t in_disk, uint8_t fds_regs_5, uint8_t data_bus);

/**
 * Compute the next `SelectDisk` value after the user presses the
 * disk-swap key.  Mirrors `FCEU_FDSSelect` line 223.
 * Returns 0 if `total_sides == 0` (defensive — C++ already guards on
 * that before calling, but the FFI must not divide by zero).
 */
uint8_t fceux11_rust_fds_compute_select_disk_next(uint8_t current, uint8_t total_sides);

/**
 * Compute the state changes for a write to $4025.
 *
 * The result describes three independent conditions, each of which
 * the C++ side acts on in sequence:
 *   - `motor_on_edge`: bit 6 transitioned 0→1.  C++ must reset
 *     `mapperFDS_diskaccess` to 0, advance `mapperFDS_blockstart`
 *     by the current `mapperFDS_diskaddr`, zero `mapperFDS_diskaddr`,
 *     set `mapperFDS_block` to `new_block`, set `mapperFDS_blocklen`
 *     to `new_blocklen`, and set `DiskSeekIRQ` to 150.
 *   - `transfer_reset`: bit 1 is set.  C++ must zero
 *     `mapperFDS_block`/`blockstart`/`blocklen`/`diskaddr` and set
 *     `DiskSeekIRQ` to 150.  If both `motor_on_edge` and
 *     `transfer_reset` fire, transfer-reset wins for the block fields.
 *   - `motor_on`: bit 6 is set in the new value (regardless of edge).
 *     C++ sets `DiskSeekIRQ = 150` (no-op if either of the above
 *     already did so).
 *
 * If `disk_inserted == 0`, all three flags are false (the C++ guards
 * the whole block on `mapperFDS_diskinsert`).
 */
struct FceuFdsWrite4025Result fceux11_rust_fds_compute_write_4025(uint8_t current_block,
                                                                  uint16_t current_filesize,
                                                                  uint8_t current_control,
                                                                  uint8_t value,
                                                                  uint8_t disk_inserted);

/**
 * Clean garbage signatures out of an iNES header.
 * `header_bytes` must point to at least 16 writable bytes.
 */
void fceux11_rust_ines_header_cleanup(uint8_t *header_bytes);

/**
 * Return the human-readable name for a mapper number.
 * Returns a pointer to a static string, or null if not found.
 */
const char *fceux11_rust_ines_mapper_name(int32_t mapper_no);

/**
 * Returns 1 if the mapper is in the not_power2 list.
 */
int32_t fceux11_rust_ines_not_power2(int32_t mapper_no);

/**
 * Look up default input controllers by ROM CRC32.
 * Returns 1 if found, 0 otherwise. Results are written to out_* params.
 */
int32_t fceux11_rust_ines_lookup_input_crc(uint32_t crc32,
                                           int32_t *out_input1,
                                           int32_t *out_input2,
                                           int32_t *out_inputfc);

/**
 * Look up default input controllers by NES 2.0 expansion device byte.
 * Returns 1 if found, 0 otherwise.
 * `out_eoptions_flag` is set to 32768 when expansion == 0x02 (Four-Score hack).
 * `out_vs_cswitch` is set to 1 when expansion == 0x05.
 */
int32_t fceux11_rust_ines_lookup_input_nes20(uint8_t expansion,
                                             int32_t *out_input1,
                                             int32_t *out_input2,
                                             int32_t *out_inputfc,
                                             int32_t *out_eoptions_flag,
                                             int32_t *out_vs_cswitch);

/**
 * Check whether a ROM is known to be bad/corrupt/hacked.
 * Returns a pointer to a static description string, or null if OK.
 */
const char *fceux11_rust_ines_check_bad(uint64_t md5partial);

/**
 * Check ROM-correction databases and return recommended fixes.
 * C++ applies the fixes to its global state.
 */
int32_t fceux11_rust_ines_check_hinfo(uint32_t crc32,
                                      uint64_t partialmd5,
                                      struct FceuInesHInfoResult *out);

/**
 * Parse an FM2 file from raw bytes.
 * Returns an opaque handle to `FceuMovieData`, or null on error.
 */
struct FceuMovieData *fceux11_rust_movie_load_fm2(const uint8_t *data,
                                                  uintptr_t len,
                                                  bool stop_after_header);

/**
 * Free a `FceuMovieData` handle obtained from `fceux11_rust_movie_load_fm2`.
 */
void fceux11_rust_movie_data_free(struct FceuMovieData *md);

int32_t fceux11_rust_movie_data_version(const struct FceuMovieData *md);

int32_t fceux11_rust_movie_data_emu_version(const struct FceuMovieData *md);

int32_t fceux11_rust_movie_data_fds(const struct FceuMovieData *md);

bool fceux11_rust_movie_data_pal_flag(const struct FceuMovieData *md);

bool fceux11_rust_movie_data_ppu_flag(const struct FceuMovieData *md);

int32_t fceux11_rust_movie_data_rerecord_count(const struct FceuMovieData *md);

bool fceux11_rust_movie_data_binary_flag(const struct FceuMovieData *md);

int32_t fceux11_rust_movie_data_load_frame_count(const struct FceuMovieData *md);

bool fceux11_rust_movie_data_fourscore(const struct FceuMovieData *md);

bool fceux11_rust_movie_data_microphone(const struct FceuMovieData *md);

int32_t fceux11_rust_movie_data_ram_init_option(const struct FceuMovieData *md);

int32_t fceux11_rust_movie_data_ram_init_seed(const struct FceuMovieData *md);

void fceux11_rust_movie_data_ports(const struct FceuMovieData *md, int32_t *out);

void fceux11_rust_movie_data_rom_checksum(const struct FceuMovieData *md, uint8_t *out);

const char *fceux11_rust_movie_data_rom_filename(const struct FceuMovieData *md);

const char *fceux11_rust_movie_data_guid(const struct FceuMovieData *md);

uintptr_t fceux11_rust_movie_data_records_count(const struct FceuMovieData *md);

bool fceux11_rust_movie_data_record_get(const struct FceuMovieData *md,
                                        uintptr_t index,
                                        struct FceuMovieRecord *out);

uintptr_t fceux11_rust_movie_data_savestate_len(const struct FceuMovieData *md);

uintptr_t fceux11_rust_movie_data_savestate_copy(const struct FceuMovieData *md,
                                                 uint8_t *out,
                                                 uintptr_t out_len);

uintptr_t fceux11_rust_movie_data_saveram_len(const struct FceuMovieData *md);

uintptr_t fceux11_rust_movie_data_saveram_copy(const struct FceuMovieData *md,
                                               uint8_t *out,
                                               uintptr_t out_len);

uintptr_t fceux11_rust_movie_data_comments_count(const struct FceuMovieData *md);

const char *fceux11_rust_movie_data_comment_get(const struct FceuMovieData *md, uintptr_t index);

uintptr_t fceux11_rust_movie_data_subtitles_count(const struct FceuMovieData *md);

const char *fceux11_rust_movie_data_subtitle_get(const struct FceuMovieData *md, uintptr_t index);

/**
 * Dump movie data to an `EmuFileMem` handle.
 * Returns the number of bytes written, or -1 on error.
 * If `seek_to_curr_frame_pos` is true and a frame position is recorded,
 * `out_curr_frame_pos` is set to that position; otherwise it is set to -1.
 */
int32_t fceux11_rust_movie_data_dump(const struct FceuMovieDataInput *input,
                                     struct EmuFileMem *out_handle,
                                     bool binary,
                                     bool seek_to_curr_frame_pos,
                                     int32_t curr_frame_counter,
                                     int32_t *out_curr_frame_pos);

/**
 * Validate an NSF header: check the "NESM\x1a" signature, ensure
 * text fields are null-terminated, and extract 16-bit addresses.
 * Returns `true` if the header is valid.
 */
bool fceux11_rust_nsf_header_validate(struct FceuNsfHeader *header,
                                      uint16_t *out_load_addr,
                                      uint16_t *out_init_addr,
                                      uint16_t *out_play_addr);

/**
 * Compute NSFMaxBank (before the decrement) and BSon/BankSwitch
 * from the header and raw NSF data size.
 */
bool fceux11_rust_nsf_compute_banks(const struct FceuNsfHeader *header,
                                    uint32_t nsf_size,
                                    uint32_t *out_nsf_max_bank,
                                    uint8_t *out_bson,
                                    uint8_t *out_bank_switch);

/**
 * Patch the NSFROM bootstrap ROM with Init and Play addresses.
 * `nsfrom` must point to at least `nsfrom_len` bytes.
 * Returns `true` if the patch was applied successfully.
 */
bool fceux11_rust_nsf_patch_nsfrom(uint8_t *nsfrom,
                                   uintptr_t nsfrom_len,
                                   uint16_t init_addr,
                                   uint16_t play_addr);

/**
 * Return the expansion chip name for a sound chip bitmask.
 * If a chip is recognised, writes the single-bit mask to `*out_mask`
 * and returns a pointer to a static thread-local C string.
 * Returns null if no recognised chip is set.
 */
const char *fceux11_rust_nsf_chip_name(uint8_t sound_chip, uint8_t *out_mask);

/**
 * Safely change the current song number.
 * Returns the clamped new song number and sets `*out_reload` to 0xFF.
 */
int32_t fceux11_rust_nsf_change_song(int32_t current,
                                     int32_t amount,
                                     int32_t total,
                                     uint8_t *out_reload);

/**
 * Copy NSF metadata strings into caller-provided buffers.
 * `maxlen` is the maximum number of bytes to copy (including null terminator).
 * Returns `TotalSongs`.
 */
int32_t fceux11_rust_nsf_get_info(const struct FceuNsfHeader *header,
                                  uint8_t *name,
                                  uint8_t *artist,
                                  uint8_t *copyright,
                                  uintptr_t maxlen);

/**
 * Look up a UNIF board by name.
 * Returns a pointer to a static `UnifBoardInfo` if found, or null otherwise.
 */
const struct UnifBoardInfo *fceux11_rust_unif_lookup_board(const char *name);

/**
 * Return the hardware flags for a given UNIF board name.
 * Returns -1 if the board is not found.
 */
int32_t fceux11_rust_unif_board_flags(const char *name);

/**
 * Compute CHR-RAM size in bytes from board flags.
 */
uint32_t fceux11_rust_unif_chrram_size(int32_t flags);

/**
 * Look up a VS UniSystem game by its partial MD5 hash.
 * Returns a pointer to a static `VsUniEntry` if found, or null otherwise.
 */
const struct VsUniEntry *fceux11_rust_vsuni_lookup(uint64_t md5partial);

/**
 * Toggle a DIP switch bit. Returns the new vsdip value.
 */
uint8_t fceux11_rust_vsuni_toggle_dip(uint8_t game_type, uint8_t vsdip, int32_t w);

/**
 * Return coin-on duration (6 frames) for a slot.
 */
uint8_t fceux11_rust_vsuni_coin(uint8_t game_type, uint8_t _slot);

/**
 * Return service-button duration (6 frames).
 */
uint8_t fceux11_rust_vsuni_service(uint8_t game_type);

/**
 * Draw the VS UniSystem DIP-switch overlay into the pixel buffer.
 * Returns the decremented `dips_howlong` value (or -1 if nothing drawn).
 */
int32_t fceux11_rust_vsuni_draw(uint8_t *xbuf, uint8_t vsdip, int32_t dips_howlong);
/**
 * `0x10000 / 8` bytes — one bit per NES address.
 */

/**
 * Flag bits packed into the high bits of each `CheatComp` slot.
 */










































/**
 * Opaque handle for the .nl parser iterator.
 */
typedef struct NlParseIter NlParseIter;

/**
 * Output struct for reading a cheat entry. Strings are returned as
 * `*const c_char` pointing into Rust-owned storage; the pointer is valid
 * until the next mutating cheat-list call.
 */
typedef struct FceuCheatEntryView {
  const char *name_ptr;
  uintptr_t name_len;
  uint32_t addr;
  uint8_t val;
  int32_t compare;
  int32_t status;
  int32_t type_;
} FceuCheatEntryView;

/**
 * POD bulk-transfer view of all six DebuggerState fields. Layout-compatible
 * with the C++ `FceuDebuggerStateView` struct.
 */
typedef struct FceuDebuggerStateView {
  bool step;
  bool stepout;
  bool runline;
  uint64_t runline_end_time;
  bool badopbreak;
  int32_t jsrcount;
} FceuDebuggerStateView;

/**
 * Result of one `log_cd_data` call. The C++ side uses these flags to
 * decide whether to trigger `BreakHit` and to update its file-static
 * `indirectnext`.
 */
typedef struct FceuLogCdDataResult {
  bool new_code_hit;
  bool new_data_hit;
  bool indirect_out;
} FceuLogCdDataResult;

/**
 * Layout-compatible POD view of one `Sym` for C++ consumption. All pointer
 * fields borrow from the [`Database`] cache and remain valid until the
 * containing [`ld65_close`] call.
 */
typedef struct FceuLd65Sym {
  uint32_t id;
  const char *name_ptr;
  uintptr_t name_len;
  int32_t size;
  int32_t value;
  /**
   * `0` = IMPORT, `1` = LABEL, `2` = EQU.
   */
  int32_t sym_type;
  /**
   * Non-zero iff `segment_*` fields are populated.
   */
  int32_t has_segment;
  int32_t segment_ofs;
  const char *segment_name_ptr;
  uintptr_t segment_name_len;
  int32_t has_scope;
  const char *scope_full_name_ptr;
  uintptr_t scope_full_name_len;
} FceuLd65Sym;

/**
 * Assemble 6502 assembly text into opcode bytes.
 * `output` must have room for at least 3 bytes.
 * Returns 0 on success, 1 on error.
 */
int32_t fceux11_rust_asm_assemble(uint8_t *output, int32_t addr, const char *str);

/**
 * Disassemble a 6502 opcode into a string.
 * Writes to `out_buf` with max `out_buf_size` bytes.
 * Returns bytes written (including null terminator), or -1 on error.
 */
int32_t fceux11_rust_asm_disassemble(int32_t _addr,
                                     const uint8_t *opcode,
                                     char *out_buf,
                                     int32_t out_buf_size);

/**
 * Add a new cheat entry. `name` may be NULL (treated as empty string).
 * Returns the new entry index (always `>= 0`).
 */
int32_t fceux11_rust_cheat_add(const char *name,
                               uint32_t addr,
                               uint8_t val,
                               int32_t compare,
                               int32_t status,
                               int32_t type_);

/**
 * Delete the cheat at `which`. Returns `1` on success, `0` if out of range.
 */
int32_t fceux11_rust_cheat_delete(uint32_t which);

/**
 * Toggle a cheat's enabled status. Returns the new status (`0`/`1`) or
 * `-1` if the index is out of range.
 */
int32_t fceux11_rust_cheat_toggle(uint32_t which);

/**
 * Disable every cheat without removing them. Returns the count of cheats
 * that were previously enabled (matches C++ behaviour).
 */
int32_t fceux11_rust_cheat_disable_all(void);

/**
 * Remove every cheat entry. Always returns `0`.
 */
int32_t fceux11_rust_cheat_delete_all(void);

/**
 * Return the current number of cheat entries.
 */
uint32_t fceux11_rust_cheat_count(void);

/**
 * Fetch the cheat at `which` into `out`. Returns `1` on success, `0` if out
 * of range. The `name_ptr` field points into a thread-local cache and is
 * invalidated by the next call.
 */
int32_t fceux11_rust_cheat_get(uint32_t which, struct FceuCheatEntryView *out);

/**
 * Update an existing cheat entry. Any negative arg leaves that field
 * untouched (same convention as the original `FCEUI_SetCheat`).
 *
 * * `name` — NULL means "do not change".
 * * `a`, `v`, `s` — values `< 0` mean "do not change".
 * * `c` — values `< -1` mean "do not change"; `-1` clears compare.
 * * `type_` is always applied.
 *
 * Returns `1` on success, `0` if out of range.
 */
int32_t fceux11_rust_cheat_set(uint32_t which,
                               const char *name,
                               int32_t a,
                               int32_t v,
                               int32_t c,
                               int32_t s,
                               int32_t type_);

/**
 * Set the `globalCheatDisabled` flag. Returns the prior value.
 */
int32_t fceux11_rust_cheat_set_global_disabled(int32_t disabled);

/**
 * Return the current `globalCheatDisabled` flag.
 */
int32_t fceux11_rust_cheat_get_global_disabled(void);

/**
 * Decode a Game Genie code. Returns `1` on success, `0` on failure.
 */
int32_t fceux11_rust_cheat_decode_gg(const char *str_ptr,
                                     int32_t *a_out,
                                     int32_t *v_out,
                                     int32_t *c_out);

/**
 * Decode a Pro Action Replay code. Returns `1` on success, `0` on failure.
 */
int32_t fceux11_rust_cheat_decode_par(const char *str_ptr,
                                      int32_t *a_out,
                                      int32_t *v_out,
                                      int32_t *c_out,
                                      int32_t *type_out);

/**
 * Allocate the cheat-map buffer (8 KiB, one bit per address). Idempotent —
 * repeat calls leave the existing buffer in place.
 */
void fceux11_rust_cheat_map_create(void);

/**
 * Release the cheat-map buffer. Idempotent.
 */
void fceux11_rust_cheat_map_release(void);

/**
 * Clear all cheat-map bits (without releasing the buffer). The caller must
 * then re-mark currently-active cheats via `fceux11_rust_cheat_map_set`.
 */
void fceux11_rust_cheat_map_refresh_clear(void);

/**
 * Return `1` if the cheat bit for `address` is set, `0` otherwise.
 * Returns `0` if the cheat map has not been created.
 */
int32_t fceux11_rust_cheat_map_find(uint16_t address);

/**
 * Set or toggle the cheat bit for `address`.
 *
 * The original C++ uses a ternary that is asymmetric:
 * `cheat ? bitmap |= mask : bitmap ^= mask`. We preserve that exact
 * behaviour — `cheat==1` sets, `cheat==0` toggles (XOR).
 */
void fceux11_rust_cheat_map_set(uint16_t address, int32_t cheat);

/**
 * Count the cheat-map bits set in the half-open range `[address, address+size)`.
 */
uint32_t fceux11_rust_cheat_map_count_affected(uint32_t address, uint32_t size);

/**
 * Allocate the cheat-comp buffer initialised to `CHEATC_NONE`. Idempotent —
 * existing values are preserved.
 */
int32_t fceux11_rust_cheat_comp_init(void);

/**
 * Release the cheat-comp buffer (matches `FCEU_FlushGameCheats` cleanup).
 */
void fceux11_rust_cheat_comp_release(void);

/**
 * Return `1` if the cheat-comp buffer exists.
 */
int32_t fceux11_rust_cheat_comp_exists(void);

/**
 * Begin a search: for every address that has a backing RAM ptr in C++ (the
 * caller passes `mem_present[i]` non-zero), store the current memory value;
 * for addresses with no backing, store `CHEATC_NONE`.
 *
 * `mem` is a `0x10000`-byte snapshot of CPU memory.
 * `mem_present` is a `0x10000`-byte boolean array: `1` if the address has a
 * `CheatRPtrs` entry (i.e. is a real RAM byte), `0` otherwise.
 */
int32_t fceux11_rust_cheat_comp_search_begin(const uint8_t *mem, const uint8_t *mem_present);

/**
 * Set every non-NOSHOW slot to the current memory value (used when
 * "Restart search" is requested without resetting flags).
 *
 * Mirrors C++ `FCEUI_CheatSearchSetCurrentAsOriginal`:
 * for visible slots, `comp[x] = mem[x]` if backed, else OR-in `CHEATC_NONE`.
 */
int32_t fceux11_rust_cheat_comp_set_current_as_original(const uint8_t *mem,
                                                        const uint8_t *mem_present);

/**
 * Clear the `CHEATC_EXCLUDED` flag from every slot.
 */
void fceux11_rust_cheat_comp_show_excluded(void);

/**
 * Return the number of "visible" search hits — slots that are neither
 * NOSHOW nor masked by the C++ presence array.
 */
int32_t fceux11_rust_cheat_comp_count(const uint8_t *mem_present);

/**
 * Read a single `CheatComp` slot. Returns `0xFFFFFFFF` if the buffer is not
 * allocated.
 */
uint32_t fceux11_rust_cheat_comp_get(uint32_t address);

/**
 * Apply a `FCEUI_CheatSearchEnd` filter using `type` and the operand bytes
 * `v1`/`v2`. Marks excluded slots with `CHEATC_EXCLUDED`.
 */
int32_t fceux11_rust_cheat_comp_search_end(int32_t search_type,
                                           uint8_t v1,
                                           uint8_t v2,
                                           const uint8_t *mem,
                                           const uint8_t *mem_present);

/**
 * Parse a condition expression string into an AST.
 * Returns an opaque pointer to the ConditionAst, or null on error.
 * Format: <subject><op><value> where subject is a flag/register/address.
 */
void *fceux11_rust_conddebug_generate_condition(const char *str);

/**
 * Destroy a ConditionAst previously returned by fceux11_rust_conddebug_generate_condition.
 */
void fceux11_rust_conddebug_condition_destroy(void *condition);

bool fceux11_rust_debug_dbgstate_get_step(void);

void fceux11_rust_debug_dbgstate_set_step(bool v);

bool fceux11_rust_debug_dbgstate_get_stepout(void);

void fceux11_rust_debug_dbgstate_set_stepout(bool v);

bool fceux11_rust_debug_dbgstate_get_runline(void);

void fceux11_rust_debug_dbgstate_set_runline(bool v);

uint64_t fceux11_rust_debug_dbgstate_get_runline_end_time(void);

void fceux11_rust_debug_dbgstate_set_runline_end_time(uint64_t v);

bool fceux11_rust_debug_dbgstate_get_badopbreak(void);

void fceux11_rust_debug_dbgstate_set_badopbreak(bool v);

int32_t fceux11_rust_debug_dbgstate_get_jsrcount(void);

void fceux11_rust_debug_dbgstate_set_jsrcount(int32_t v);

/**
 * Pre-increment `jsrcount`. Returns the new value.
 */
int32_t fceux11_rust_debug_dbgstate_jsrcount_inc(void);

/**
 * Pre-decrement `jsrcount`. Returns the new value.
 */
int32_t fceux11_rust_debug_dbgstate_jsrcount_dec(void);

/**
 * Reset to defaults — equivalent to C++ `DebuggerState::reset()`:
 * step=false, stepout=false, jsrcount=0. Note: the C++ reset does NOT
 * touch runline / runline_end_time / badopbreak (matches C++).
 */
void fceux11_rust_debug_dbgstate_reset(void);

/**
 * Snapshot all six fields into `out`. Useful for the GUI Step-Out block in
 * `ConsoleDebugger.cpp:3029-3055` which previously held a `DebuggerState&`.
 */
void fceux11_rust_debug_dbgstate_copy_out(struct FceuDebuggerStateView *out);

/**
 * Bulk-write all six fields.
 */
void fceux11_rust_debug_dbgstate_copy_in(const struct FceuDebuggerStateView *in_);

uint8_t fceux11_rust_debug_evaluate_write(uint8_t opwrite_byte,
                                          uint16_t address,
                                          uint8_t a,
                                          uint8_t x,
                                          uint8_t y,
                                          uint8_t p,
                                          uint8_t s,
                                          uint8_t mem_at_addr);

int32_t fceux11_rust_debug_get_value(int32_t reg_or_flag,
                                     uint8_t a,
                                     uint8_t x,
                                     uint8_t y,
                                     uint8_t p,
                                     uint16_t pc,
                                     uint8_t s);

void fceux11_rust_debug_log_cd_vectors(uint8_t *cdloggerdata,
                                       uintptr_t cdloggerdata_size,
                                       int32_t prg_addr,
                                       int32_t *codecount,
                                       int32_t *datacount,
                                       int32_t *undefinedcount);

struct FceuLogCdDataResult fceux11_rust_debug_log_cd_data(uint8_t *cdloggerdata,
                                                          uintptr_t cdloggerdata_size,
                                                          int32_t pc_prg_addr,
                                                          int32_t a_prg_addr,
                                                          uint16_t pc,
                                                          uint16_t a,
                                                          uint8_t opcode0,
                                                          uint8_t optype_byte,
                                                          uint8_t opwrite_byte,
                                                          uintptr_t size,
                                                          bool indirect_in,
                                                          int32_t *codecount,
                                                          int32_t *datacount,
                                                          int32_t *undefinedcount);

/**
 * Generate the `.nl` filename for `(rom_file, bank)`. Writes the result into
 * `out`/`out_cap` as a null-terminated string. Returns bytes written
 * (excluding NUL), or `-1` on null pointer / zero capacity.
 */
int32_t fceux11_rust_debugsym_nl_filename_for_bank(const char *rom_file,
                                                   int32_t bank,
                                                   char *out,
                                                   uintptr_t out_cap);

/**
 * Parse `.nl` content (UTF-8) and return an opaque iterator. Caller must
 * call `parse_end` to free. `content_ptr` may be null only if `content_len == 0`.
 */
struct NlParseIter *fceux11_rust_debugsym_parse_begin(const char *content_ptr,
                                                      uintptr_t content_len);

/**
 * Advance the iterator. Fills `out_ofs`, `out_name`, `out_comment` (each as
 * null-terminated string into the given buffer). Returns `true` if an entry
 * was produced, `false` if the iterator is exhausted or any output pointer
 * is invalid.
 */
bool fceux11_rust_debugsym_parse_next(struct NlParseIter *it,
                                      uint32_t *out_ofs,
                                      char *out_name,
                                      uintptr_t out_name_cap,
                                      char *out_comment,
                                      uintptr_t out_comment_cap);

/**
 * Free the iterator returned by `parse_begin`.
 */
void fceux11_rust_debugsym_parse_end(struct NlParseIter *it);

/**
 * Write `entries` to `path` as a `.nl` file. Returns `0` on success,
 * `-1` on I/O failure or invalid argument.
 */
int32_t fceux11_rust_debugsym_save_nl_file(const char *path,
                                           const uint32_t *ofs_arr,
                                           const char *const *name_arr,
                                           const char *const *comment_arr,
                                           uintptr_t count);

/**
 * Number of register map entries.
 */
uint32_t fceux11_rust_debugsym_register_map_count(void);

/**
 * Fetch register map entry `idx`. Returns `true` on success.
 */
bool fceux11_rust_debugsym_register_map_get(uint32_t idx,
                                            uint32_t *out_ofs,
                                            char *out_name,
                                            uintptr_t out_name_cap);

/**
 * Format `name[idx]` into `out`/`out_cap`. Returns bytes written.
 */
int32_t fceux11_rust_debugsym_format_array_index(const char *name,
                                                 int32_t idx,
                                                 char *out,
                                                 uintptr_t out_cap);

/**
 * Trim trailing whitespace in a null-terminated C string in place.
 * Returns the new length.
 */
int32_t fceux11_rust_debugsym_trim_trailing_inplace(char *buf);

/**
 * Open a `.dbg` file and parse it. Returns an opaque handle, or `NULL` on
 * error (call [`ld65_last_error`] for the reason).
 */
void *fceux11_rust_ld65_open(const char *path);

/**
 * Free a database returned by [`ld65_open`].
 */
void fceux11_rust_ld65_close(void *db);

/**
 * Number of symbols in the database.
 */
uint32_t fceux11_rust_ld65_sym_count(void *db);

/**
 * Fill `out` with the symbol at index `idx`. Returns `true` on success.
 */
bool fceux11_rust_ld65_sym_get(void *db, uint32_t idx, struct FceuLd65Sym *out);

/**
 * Callback-style iteration matching the legacy `database::iterateSymbols`
 * signature. `cb` is called once per symbol (in id order) with `user_data`
 * echoed back. Returns the number of symbols iterated.
 */
uint32_t fceux11_rust_ld65_iterate(void *db,
                                   void *user_data,
                                   void (*cb)(void*, const struct FceuLd65Sym*));

/**
 * Return the most recent error message produced by [`ld65_open`], or `NULL`
 * if there isn't one.
 */
const char *fceux11_rust_ld65_last_error(void);
extern uint8_t fceux11_lua_GetMem(uint32_t addr);

extern void fceux11_lua_BWrite(uint32_t addr, uint8_t val);

extern uint16_t fceux11_lua_GetRegister(int32_t reg_id);

extern uint32_t fceux11_lua_GetJoypadState(int32_t port);

extern void fceux11_lua_SetJoypadOverride(int32_t port, uint32_t mask1, uint32_t mask2);

extern int32_t fceux11_lua_GetRomMD5(uint8_t *buf);

extern uint8_t fceux11_lua_ReadRomByte(uint32_t addr);

extern void fceux11_lua_WriteRomByte(uint32_t addr, uint8_t val);

extern uint8_t fceux11_lua_PPURead(uint32_t addr);

extern int32_t fceux11_lua_movie_get_mode(void);

extern int64_t fceux11_lua_movie_get_rerecordcount(void);

extern int64_t fceux11_lua_movie_get_length(void);

extern void fceux11_lua_movie_stop(void);

extern int32_t fceux11_lua_movie_get_readonly(void);

extern void fceux11_lua_movie_set_readonly(int32_t val);

extern int32_t fceux11_lua_movie_is_poweron(void);

extern int32_t fceux11_lua_movie_is_from_savestate(void);

extern const char *fceux11_lua_movie_get_name(void);

extern const char *fceux11_lua_movie_get_filename(void);

extern int32_t fceux11_lua_savestate_save_slot(int32_t slot);

extern int32_t fceux11_lua_savestate_load_slot(int32_t slot);

extern int64_t fceux11_lua_emu_get_framecount(void);

extern int64_t fceux11_lua_emu_get_lagcount(void);

extern int32_t fceux11_lua_emu_is_paused(void);

extern void fceux11_lua_emu_set_speedmode(int32_t mode);

extern void fceux11_lua_emu_poweron(void);

extern void fceux11_lua_emu_softreset(void);

extern void fceux11_lua_emu_message(const char *msg);

extern void fceux11_lua_emu_pause(void);

extern void fceux11_lua_emu_unpause(void);

extern int32_t fceux11_lua_savestate_create_object(const char *path,
                                                   int32_t which,
                                                   int32_t anonymous);

extern void fceux11_lua_savestate_delete_object(int32_t obj_id);

extern int32_t fceux11_lua_savestate_object_save(int32_t obj_id);

extern int32_t fceux11_lua_savestate_object_load(int32_t obj_id);

extern int32_t fceux11_lua_savestate_object_persist(int32_t obj_id);

extern void fceux11_lua_gui_popup(const char *msg);

extern void fceux11_lua_gui_savescreenshot(const char *filename);

extern double fceux11_lua_sound_get_square1_volume(void);

extern double fceux11_lua_sound_get_square1_frequency(void);

extern double fceux11_lua_sound_get_square1_midikey(void);

extern int32_t fceux11_lua_sound_get_square1_duty(void);

extern int32_t fceux11_lua_sound_get_square1_regs(void);

extern double fceux11_lua_sound_get_square2_volume(void);

extern double fceux11_lua_sound_get_square2_frequency(void);

extern double fceux11_lua_sound_get_square2_midikey(void);

extern int32_t fceux11_lua_sound_get_square2_duty(void);

extern int32_t fceux11_lua_sound_get_square2_regs(void);

extern double fceux11_lua_sound_get_triangle_volume(void);

extern int32_t fceux11_lua_sound_get_triangle_linear(void);

extern double fceux11_lua_sound_get_triangle_frequency(void);

extern double fceux11_lua_sound_get_triangle_midikey(void);

extern double fceux11_lua_sound_get_noise_volume(void);

extern int32_t fceux11_lua_sound_get_noise_mode(void);

extern int32_t fceux11_lua_sound_get_noise_regs(void);

extern double fceux11_lua_sound_get_noise_frequency(void);

extern double fceux11_lua_sound_get_noise_midikey(void);

extern double fceux11_lua_sound_get_dmc_volume(void);

extern int32_t fceux11_lua_sound_get_dmc_rate(void);

extern int32_t fceux11_lua_sound_get_dmc_regs(void);

extern double fceux11_lua_sound_get_dmc_frequency(void);

extern double fceux11_lua_sound_get_dmc_midikey(void);

extern int32_t fceux11_lua_sound_get_dmc_address(void);

extern int32_t fceux11_lua_sound_get_dmc_size(void);

extern int32_t fceux11_lua_sound_get_dmc_loop(void);

extern int32_t fceux11_lua_sound_get_dmc_seed(void);

extern int32_t fceux11_lua_sound_get_frame_sequencer(void);

extern int32_t fceux11_lua_sound_get_sample_rate(void);

extern int32_t fceux11_lua_sound_get_length_count(void);

extern int32_t fceux11_lua_zapper_get_x(void);

extern int32_t fceux11_lua_zapper_get_y(void);

extern int32_t fceux11_lua_zapper_get_click(void);

extern void fceux11_lua_zapper_set(int32_t x, int32_t y, int32_t fire);

extern void fceux11_lua_debugger_hitbreakpoint(void);

extern uint64_t fceux11_lua_debugger_get_cycles_count(void);

extern uint64_t fceux11_lua_debugger_get_instructions_count(void);

extern void fceux11_lua_debugger_reset_cycles_count(void);

extern void fceux11_lua_debugger_reset_instructions_count(void);

extern int64_t fceux11_lua_debugger_get_symbol_offset(const char *name);

extern int32_t fceux11_lua_GetKeyboardState(uint8_t *keys);

extern void fceux11_lua_GetMouseState(int32_t *x, int32_t *y, int32_t *click);

extern void fceux11_lua_recalculate_mem_hook_regions(int hook_type);

int fceux11_lua_init(void);

int fceux11_lua_load_script(const char *path, const char *arg);

void fceux11_lua_frame_boundary(void);

void fceux11_lua_stop(void);

int fceux11_lua_running(void);

void fceux11_lua_gui(uint8_t *xbuf, int width, int height);

uint8_t fceux11_lua_read_joypad(int controller, uint8_t original);

int fceux11_lua_call_registered(int call_id);

void fceux11_lua_call_mem_hook(unsigned int addr, int size, unsigned int value, int hook_type);

int fceux11_lua_gui_pixel(int x, int y, unsigned int color);

int fceux11_lua_get_mem_hook_count(int hook_type);

uint32_t fceux11_lua_get_mem_hook_address(int hook_type, int index);

uint8_t fceux11_lua_GetMem(uint32_t _addr);

void fceux11_lua_BWrite(uint32_t _addr, uint8_t _val);

uint16_t fceux11_lua_GetRegister(int32_t _reg_id);

uint32_t fceux11_lua_GetJoypadState(int32_t _port);

void fceux11_lua_SetJoypadOverride(int32_t _port, uint32_t _mask1, uint32_t _mask2);

int32_t fceux11_lua_GetRomMD5(uint8_t *_buf);

uint8_t fceux11_lua_ReadRomByte(uint32_t _addr);

void fceux11_lua_WriteRomByte(uint32_t _addr, uint8_t _val);

uint8_t fceux11_lua_PPURead(uint32_t _addr);

int32_t fceux11_lua_movie_get_mode(void);

int64_t fceux11_lua_movie_get_rerecordcount(void);

int64_t fceux11_lua_movie_get_length(void);

void fceux11_lua_movie_stop(void);

int32_t fceux11_lua_movie_get_readonly(void);

void fceux11_lua_movie_set_readonly(int32_t _val);

int32_t fceux11_lua_movie_is_poweron(void);

int32_t fceux11_lua_movie_is_from_savestate(void);

const char *fceux11_lua_movie_get_name(void);

const char *fceux11_lua_movie_get_filename(void);

int32_t fceux11_lua_savestate_save_slot(int32_t _slot);

int32_t fceux11_lua_savestate_load_slot(int32_t _slot);

int64_t fceux11_lua_emu_get_framecount(void);

int64_t fceux11_lua_emu_get_lagcount(void);

int32_t fceux11_lua_emu_is_paused(void);

void fceux11_lua_emu_set_speedmode(int32_t _mode);

void fceux11_lua_emu_poweron(void);

void fceux11_lua_emu_softreset(void);

void fceux11_lua_emu_message(const char *_msg);

void fceux11_lua_emu_pause(void);

void fceux11_lua_emu_unpause(void);

int32_t fceux11_lua_savestate_create_object(const char *_path, int32_t _which, int32_t _anonymous);

void fceux11_lua_savestate_delete_object(int32_t _obj_id);

int32_t fceux11_lua_savestate_object_save(int32_t _obj_id);

int32_t fceux11_lua_savestate_object_load(int32_t _obj_id);

int32_t fceux11_lua_savestate_object_persist(int32_t _obj_id);

void fceux11_lua_gui_popup(const char *_msg);

void fceux11_lua_gui_savescreenshot(const char *_filename);

double fceux11_lua_sound_get_square1_volume(void);

double fceux11_lua_sound_get_square1_frequency(void);

double fceux11_lua_sound_get_square1_midikey(void);

int32_t fceux11_lua_sound_get_square1_duty(void);

int32_t fceux11_lua_sound_get_square1_regs(void);

double fceux11_lua_sound_get_square2_volume(void);

double fceux11_lua_sound_get_square2_frequency(void);

double fceux11_lua_sound_get_square2_midikey(void);

int32_t fceux11_lua_sound_get_square2_duty(void);

int32_t fceux11_lua_sound_get_square2_regs(void);

double fceux11_lua_sound_get_triangle_volume(void);

int32_t fceux11_lua_sound_get_triangle_linear(void);

double fceux11_lua_sound_get_triangle_frequency(void);

double fceux11_lua_sound_get_triangle_midikey(void);

double fceux11_lua_sound_get_noise_volume(void);

int32_t fceux11_lua_sound_get_noise_mode(void);

int32_t fceux11_lua_sound_get_noise_regs(void);

double fceux11_lua_sound_get_noise_frequency(void);

double fceux11_lua_sound_get_noise_midikey(void);

double fceux11_lua_sound_get_dmc_volume(void);

int32_t fceux11_lua_sound_get_dmc_rate(void);

int32_t fceux11_lua_sound_get_dmc_regs(void);

double fceux11_lua_sound_get_dmc_frequency(void);

double fceux11_lua_sound_get_dmc_midikey(void);

int32_t fceux11_lua_sound_get_dmc_address(void);

int32_t fceux11_lua_sound_get_dmc_size(void);

int32_t fceux11_lua_sound_get_dmc_loop(void);

int32_t fceux11_lua_sound_get_dmc_seed(void);

int32_t fceux11_lua_sound_get_frame_sequencer(void);

int32_t fceux11_lua_sound_get_sample_rate(void);

int32_t fceux11_lua_sound_get_length_count(void);

int32_t fceux11_lua_zapper_get_x(void);

int32_t fceux11_lua_zapper_get_y(void);

int32_t fceux11_lua_zapper_get_click(void);

void fceux11_lua_zapper_set(int32_t _x, int32_t _y, int32_t _fire);

void fceux11_lua_debugger_hitbreakpoint(void);

uint64_t fceux11_lua_debugger_get_cycles_count(void);

uint64_t fceux11_lua_debugger_get_instructions_count(void);

void fceux11_lua_debugger_reset_cycles_count(void);

void fceux11_lua_debugger_reset_instructions_count(void);

int64_t fceux11_lua_debugger_get_symbol_offset(const char *_name);

int32_t fceux11_lua_GetKeyboardState(uint8_t *_keys);

void fceux11_lua_GetMouseState(int32_t *_x, int32_t *_y, int32_t *_click);

void fceux11_lua_recalculate_mem_hook_regions(int _hook_type);
/**
 * Input chunk descriptor for saving.
 */
typedef struct FceuStateChunkInput {
  uint8_t chunk_type;
  const uint8_t *data;
  uintptr_t len;
} FceuStateChunkInput;

/**
 * Buffer descriptor returned by save / used by free.
 */
typedef struct FceuStateBuffer {
  uint8_t *ptr;
  uintptr_t len;
  uintptr_t cap;
} FceuStateBuffer;

/**
 * Output chunk descriptor for loading.
 */
typedef struct FceuStateChunkOutput {
  uint8_t chunk_type;
  uint8_t *data;
  uintptr_t len;
} FceuStateChunkOutput;

/**
 * Serialize chunks into a savestate file buffer.
 *
 * On success, returns `true` and writes a `FceuStateBuffer` to `out_buf`.
 * The caller must free `out_buf.ptr` via `fceux11_rust_state_file_buf_free`.
 */
bool fceux11_rust_state_file_save(const struct FceuStateChunkInput *chunks,
                                  uintptr_t chunk_count,
                                  uint32_t version,
                                  int32_t compression_level,
                                  struct FceuStateBuffer *out_buf);

/**
 * Deserialize a savestate file buffer into chunks.
 *
 * On success, returns `true` and writes:
 * * `out_chunks` — pointer to an array of `FceuStateChunkOutput`
 * * `out_chunk_count` — number of chunks
 * * `out_version` — savestate version from header
 * * `out_totalsize` — uncompressed payload size
 *
 * The caller must free `out_chunks` via `fceux11_rust_state_file_chunks_free`.
 */
bool fceux11_rust_state_file_load(const uint8_t *file_data,
                                  uintptr_t file_len,
                                  struct FceuStateChunkOutput **out_chunks,
                                  uintptr_t *out_chunk_count,
                                  uint32_t *out_version,
                                  uint32_t *out_totalsize);

/**
 * Free a buffer previously returned by `fceux11_rust_state_file_save`.
 */
void fceux11_rust_state_file_buf_free(struct FceuStateBuffer buf);

/**
 * Free chunks previously returned by `fceux11_rust_state_file_load`.
 */
void fceux11_rust_state_file_chunks_free(struct FceuStateChunkOutput *chunks,
                                         uintptr_t chunk_count);
#ifdef __cplusplus
}
#endif

#endif /* FCEUX11_RUST_H */
