/* Auto-generated by cbindgen. Do not edit. */

#ifndef FCEUX11_RUST_H
#define FCEUX11_RUST_H

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* === v0.2.13 Slice types (manually appended) === */
typedef struct FceuSlice {
  const uint8_t *ptr;
  size_t len;
} FceuSlice;

typedef struct FceuSliceMut {
  uint8_t *ptr;
  size_t len;
} FceuSliceMut;

/**
 * Rust implementation of Unicode UTF conversion routines.
 * Replaces src/utils/ConvertUTF.c with a memory-safe equivalent.
 *
 * Phase 6 (v0.2.7): Unicode Conversion
 */
typedef enum ConversionResult {
  ConversionOK = 0,
  SourceExhausted = 1,
  TargetExhausted = 2,
  SourceIllegal = 3,
} ConversionResult;

typedef enum ConversionFlags {
  StrictConversion = 0,
  LenientConversion = 1,
} ConversionFlags;

typedef struct FceuGuid {
  uint8_t data[16];
} FceuGuid;

/**
 * C-compatible MD5 context layout. Must match `struct md5_context` in C++ exactly.
 */
typedef struct md5_context {
  uint32_t total[2];
  uint32_t state[4];
  uint8_t buffer[64];
} md5_context;

/**
 * C ABI: Convert UTF-8 to UTF-16.
 *
 * # Safety
 * All pointer parameters must be valid and non-null (except as noted).
 */
enum ConversionResult fceux11_rust_convert_utf8_to_utf16(const uint8_t **source_start,
                                                         const uint8_t *source_end,
                                                         uint16_t **target_start,
                                                         const uint16_t *target_end,
                                                         enum ConversionFlags flags);

/**
 * C ABI: Convert UTF-16 to UTF-8.
 *
 * # Safety
 * All pointer parameters must be valid and non-null.
 */
enum ConversionResult fceux11_rust_convert_utf16_to_utf8(const uint16_t **source_start,
                                                         const uint16_t *source_end,
                                                         uint8_t **target_start,
                                                         const uint8_t *target_end,
                                                         enum ConversionFlags flags);

/**
 * C ABI: Convert UTF-8 to UTF-32.
 *
 * # Safety
 * All pointer parameters must be valid and non-null.
 */
enum ConversionResult fceux11_rust_convert_utf8_to_utf32(const uint8_t **source_start,
                                                         const uint8_t *source_end,
                                                         uint32_t **target_start,
                                                         const uint32_t *target_end,
                                                         enum ConversionFlags flags);

/**
 * C ABI: Convert UTF-32 to UTF-8.
 *
 * # Safety
 * All pointer parameters must be valid and non-null.
 */
enum ConversionResult fceux11_rust_convert_utf32_to_utf8(const uint32_t **source_start,
                                                         const uint32_t *source_end,
                                                         uint8_t **target_start,
                                                         const uint8_t *target_end,
                                                         enum ConversionFlags flags);

/**
 * C ABI: Convert UTF-16 to UTF-32.
 *
 * # Safety
 * All pointer parameters must be valid and non-null.
 */
enum ConversionResult fceux11_rust_convert_utf16_to_utf32(const uint16_t **source_start,
                                                          const uint16_t *source_end,
                                                          uint32_t **target_start,
                                                          const uint32_t *target_end,
                                                          enum ConversionFlags flags);

/**
 * C ABI: Convert UTF-32 to UTF-16.
 *
 * # Safety
 * All pointer parameters must be valid and non-null.
 */
enum ConversionResult fceux11_rust_convert_utf32_to_utf16(const uint32_t **source_start,
                                                          const uint32_t *source_end,
                                                          uint16_t **target_start,
                                                          const uint16_t *target_end,
                                                          enum ConversionFlags flags);

/**
 * C ABI: Check whether a byte sequence is a legal UTF-8 sequence.
 *
 * # Safety
 * `source` and `source_end` must be valid pointers with `source <= source_end`.
 */
uint8_t fceux11_rust_is_legal_utf8_sequence(const uint8_t *source, const uint8_t *source_end);

/**
 * C ABI: Compute CRC32 over a byte buffer with an optional initial CRC value.
 *
 * # Safety
 * `buf` must point to at least `len` valid bytes, or be NULL when `len` is 0.
 */
uint32_t fceux11_rust_crc32(uint32_t crc, const uint8_t *buf, uint32_t len);

/**
 * C ABI: Return the next power of two for `n`.
 * If `n` is already a power of two, returns `n`.
 * For `n == 0`, returns `0` to match original C++ behavior.
 */
uint32_t fceux11_rust_uppow2(uint32_t n);

/**
 * C ABI: Generate a new random GUID (UUID v4) into the provided buffer.
 *
 * # Safety
 * `guid` must point to a valid, writable `FceuGuid`.
 */
void fceux11_rust_guid_new(struct FceuGuid *guid);

/**
 * C ABI: Convert a GUID to a hex string representation.
 *
 * # Safety
 * `guid` must point to a valid 16-byte GUID.
 * Returns a pointer to a thread-local static buffer. Caller should copy immediately.
 */
const char *fceux11_rust_guid_to_string(const struct FceuGuid *guid);

/**
 * C ABI: Parse a hex string into a GUID.
 *
 * # Safety
 * `guid` must point to a valid, writable `FceuGuid`.
 * `str` must point to a null-terminated string in the format "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX".
 */
void fceux11_rust_guid_scan(struct FceuGuid *guid,
                            const char *str);

/**
 * # Safety
 * `ctx` must point to a valid, writable `Md5Context`.
 */
void fceux11_rust_md5_starts(struct md5_context *ctx);

/**
 * # Safety
 * `ctx` must point to a valid, writable `Md5Context`.
 * `input` must point to at least `length` valid bytes, or be NULL when `length` is 0.
 */
void fceux11_rust_md5_update(struct md5_context *ctx, const uint8_t *input, uint32_t length);

/**
 * # Safety
 * `ctx` must point to a valid, writable `Md5Context`.
 * `digest` must point to at least 16 writable bytes.
 */
void fceux11_rust_md5_finish(struct md5_context *ctx, uint8_t *digest);

/**
 * # Safety
 * `md5` must point to a valid 16-byte MD5 digest.
 * Returns a pointer to a thread-local static buffer. Caller should copy immediately.
 */
const char *fceux11_rust_md5_asciistr(const uint8_t *md5);

/**
 * C ABI: Create a single directory.
 *
 * Returns 0 on success, -1 on failure.
 *
 * # Safety
 * `path` must be a valid null-terminated UTF-8 string.
 */
int32_t fceux11_rust_mkdir(const char *path);

/**
 * C ABI: Create a directory and all its parents.
 *
 * Returns 0 on success, -1 on failure.
 *
 * # Safety
 * `path` must be a valid null-terminated UTF-8 string.
 */
int32_t fceux11_rust_mkpath(const char *path);

/**
 * C ABI: Check whether a regular file exists.
 *
 * Returns 1 if the path exists and is a file, 0 otherwise.
 *
 * # Safety
 * `filepath` must be a valid null-terminated UTF-8 string.
 */
int32_t fceux11_rust_file_exists(const char *filepath);

/**
 * C ABI: Sleep for `ms` milliseconds.
 *
 * Returns 0.
 */
int32_t fceux11_rust_msleep(int32_t ms);

/**
 * C ABI: Create a new `ProfilerFuncMap` and return an opaque handle.
 */
void *fceux11_rust_profiler_map_create(void);

/**
 * C ABI: Destroy a `ProfilerFuncMap` handle.
 */
void fceux11_rust_profiler_map_destroy(void *handle);

/**
 * C ABI: Register a `funcProfileRecord*` under the key `file:line`.
 */
int fceux11_rust_profiler_map_add_record(void *handle,
                                         const char *file,
                                         int line,
                                         const char *_func,
                                         const char *_comment,
                                         void *rec);

/**
 * C ABI: Push a record pointer onto the call stack.
 */
void fceux11_rust_profiler_map_push_stack(void *handle, void *rec);

/**
 * C ABI: Pop the top of the call stack.
 */
void fceux11_rust_profiler_map_pop_stack(void *handle, void *_rec);

/**
 * C ABI: Begin iteration over the map. Returns the first record, or null.
 */
void *fceux11_rust_profiler_map_iterate_begin(void *handle);

/**
 * C ABI: Advance iteration and return the next record, or null.
 */
void *fceux11_rust_profiler_map_iterate_next(void *handle);

/**
 * C ABI: Add a C++ `profilerFuncMap*` to the global thread list.
 */
int fceux11_rust_profiler_mgr_add(void *cpp_ptr);

/**
 * C ABI: Remove a C++ `profilerFuncMap*` from the global thread list.
 *
 * `should_destroy` is ignored; destruction is handled by C++.
 */
int fceux11_rust_profiler_mgr_remove(void *cpp_ptr, int _should_destroy);

/**
 * C ABI: Clear the global thread list (called from `profilerManager` destructor).
 */
void fceux11_rust_profiler_mgr_clear(void);

/**
 * C ABI: Return the current monotonic timestamp in nanoseconds.
 *
 * The returned value is relative to an arbitrary epoch established
 * at program startup (or first call). It is guaranteed to be
 * monotonically increasing and suitable for high-precision delta
 * measurements.
 */
uint64_t fceux11_rust_timestamp_now(void);

/**
 * C ABI: Return the timestamp frequency in Hz.
 *
 * The Rust implementation uses nanosecond resolution, so the
 * frequency is always 1_000_000_000 Hz.
 */
uint64_t fceux11_rust_timestamp_freq(void);

/**
 * C ABI: Initialize the timestamp module.
 *
 * Ensures the base instant is captured. Returns 1 on success.
 */
int32_t fceux11_rust_timestamp_init(void);
/**
 * C-visible opaque type for audio filter state.
 */
typedef struct FceuFilterState {
  uint8_t _private[0];
} FceuFilterState;

typedef struct Pal {
  uint8_t r;
  uint8_t g;
  uint8_t b;
} Pal;

/**
 * C ABI: Create a new filter state and return an opaque handle.
 */
struct FceuFilterState *fceux11_rust_filter_state_create(void);

/**
 * C ABI: Destroy a filter state handle.
 */
void fceux11_rust_filter_state_destroy(struct FceuFilterState *handle);

/**
 * C ABI: Initialise FIR coefficients and resampling state.
 *
 * `ntsc_cpu` and `pal_cpu` are the base CPU clock frequencies in Hz
 * (e.g. 1789772.727… for NTSC, 1662607.125 for PAL).
 */
void fceux11_rust_filter_make(struct FceuFilterState *handle,
                              int32_t rate,
                              int32_t soundq,
                              int32_t is_pal,
                              double ntsc_cpu,
                              double pal_cpu);

/**
 * C ABI: `SexyFilter` wrapper.
 *
 * `in_buf` and `out_buf` may point to the same memory.
 */
void fceux11_rust_filter_sexy(struct FceuFilterState *handle,
                              int32_t *in_buf,
                              int32_t *out_buf,
                              int32_t count,
                              int32_t snd_rate,
                              int32_t sound_volume,
                              int32_t soundq);

/**
 * C ABI: `SexyFilter2` wrapper.
 */
void fceux11_rust_filter_sexy2(struct FceuFilterState *handle, int32_t *buf, int32_t count);

/**
 * C ABI: `NeoFilterSound` wrapper.
 *
 * Returns the number of samples written to `out`.
 * `leftover` is set to the number of samples that must be copied from the
 * end of `in` to the beginning of `in` on the next call.
 */
int32_t fceux11_rust_filter_neo(struct FceuFilterState *handle,
                                int32_t *in_buf,
                                int32_t *out_buf,
                                uint32_t inlen,
                                int32_t *leftover,
                                int32_t soundq,
                                int32_t lowpass,
                                void (*neo_fill)(int32_t*, int32_t),
                                int32_t snd_rate,
                                int32_t sound_volume);

/**
 * Compute the 64-entry NTSC base palette from tint and hue.
 * `out` must point to at least 64 `Pal` entries.
 */
void fceux11_rust_palette_calc_ntsc(int tint, int hue, struct Pal *out);

/**
 * Expand a 64-entry base palette into 512 entries with de-emphasis applied.
 * `src` must point to 64 `Pal` entries.
 * `dst` must point to 512 `Pal` entries.
 * It is safe for `src == dst` (in-place expansion).
 */
void fceux11_rust_palette_apply_deemphasis(const struct Pal *src, struct Pal *dst);

/**
 * Convert a 512-entry palette to grayscale.
 * `src` and `dst` must each point to 512 `Pal` entries.
 */
void fceux11_rust_palette_make_grayscale(const struct Pal *src, struct Pal *dst);

/**
 * Draw the NTSC tint/hue control bars into a pixel buffer.
 * `xbuf` must be a non-null pointer to an 8-bit indexed pixel buffer.
 * `width` is the horizontal stride (typically 256).
 * `which` is the bar length in pixels (typically ntschue*2 or ntsctint*2).
 */
void fceux11_rust_palette_draw_control_bars(uint8_t *xbuf, int width, int which);

/**
 * C ABI: Begin recording a wave file.
 *
 * Opens (or truncates) `path` and writes a 44-byte PCM WAV header.
 * `sample_rate` is passed explicitly from C++ to avoid reading global state.
 *
 * # Safety
 * `path` must be a valid null-terminated UTF-8 string.
 */
bool fceux11_rust_wave_begin(const char *path, uint32_t sample_rate);

/**
 * C ABI: Returns whether a wave recording is currently active.
 */
bool fceux11_rust_wave_running(void);

/**
 * C ABI: Write audio samples to the active wave file.
 *
 * `buffer` points to `count` little-endian signed 16-bit samples.
 * Returns the number of bytes written, or 0 if no file is open.
 *
 * # Safety
 * `buffer` must point to at least `count` valid `i16` samples, or be NULL when `count` is 0.
 */
int64_t fceux11_rust_wave_write(const int16_t *buffer, int32_t count);

/**
 * C ABI: Finalize and close the active wave file.
 *
 * Seeks back to the header and updates the RIFF chunk size and data chunk size.
 * Returns 1 on success, 0 if no file was open.
 */
int32_t fceux11_rust_wave_end(void);
/**
 * In-memory file buffer. Corresponds to C++ `EMUFILE_MEMORY`.
 */
typedef struct EmuFileMem EmuFileMem;

typedef struct FceuInesHeader {
  uint8_t id[4];
  uint8_t rom_size;
  uint8_t vrom_size;
  uint8_t rom_type;
  uint8_t rom_type2;
  uint8_t rom_type3;
  uint8_t upper_rom_vrom_size;
  uint8_t ram_size;
  uint8_t vram_size;
  uint8_t tv_system;
  uint8_t vs_hardware;
  uint8_t misc_roms;
  uint8_t expansion;
} FceuInesHeader;

typedef struct FceuRomSizes {
  /**
   * Number of 16 KiB PRG banks (power of two; 256 for the special
   * iNES-1 zero-size case).
   */
  uint32_t rom_size_16kb;
  /**
   * Number of 8 KiB CHR banks (power of two or iNES-2 computed).
   */
  uint32_t vrom_size_8kb;
  /**
   * CHR-RAM size in bytes.  -1 means "not applicable" (CHR-ROM
   * present).  0 means "determined later".
   */
  int32_t chrram_size;
  /**
   * Raw (not-rounded) PRG size in 16 KiB units, before .
   * Needed for non-power-of-2 ROM loading and debug printing.
   */
  uint32_t rom_size_raw;
} FceuRomSizes;

typedef struct FceuSaveGameEntry {
  uint8_t *bufptr;
  uint32_t buflen;
} FceuSaveGameEntry;

/**
 * Opaque handle for an in-memory file.
 */
typedef struct EmuFileMem *EmuFileMemHandle;

typedef struct FceuInesHInfoResult {
  int32_t mapper;
  int32_t mapper_mask;
  int32_t mirror;
  int32_t force_battery;
  int32_t clear_vrom;
} FceuInesHInfoResult;

typedef struct UnifBoardInfo {
  const char *name;
  int32_t flags;
} UnifBoardInfo;

typedef struct VsUniEntry {
  const char *name;
  uint64_t md5partial;
  int32_t mapper;
  uint8_t mirroring;
  uint8_t ppu;
  int32_t ioption;
  int32_t predip;
  uint8_t game_type;
} VsUniEntry;

/**
 * Compute `ROM_size` and `VROM_size` (in bank counts) from the iNES
 * header.  `mapper_no` is only used for the iNES-2 CHRRAM fallback.
 * Returns `true` on success.
 */
bool fceux11_rust_cart_compute_rom_sizes(const struct FceuInesHeader *header,
                                         bool is_nes2,
                                         struct FceuRomSizes *out);

/**
 * Return the default CHR-RAM size in bytes when no CHR-ROM is present.
 * For iNES-2 the caller should instead use `battery_vram_size +
 * vram_size`.  Returns -1 when CHR-ROM is present (`has_vrom` true).
 */
int32_t fceux11_rust_cart_compute_chrram_size(int32_t mapper_no,
                                              bool is_nes2,
                                              int32_t vram_size,
                                              int32_t battery_vram_size,
                                              bool has_vrom);

/**
 * Save battery-backed RAM to `path`.  Each non-null entry is written
 * sequentially.  Returns `true` on success.
 */
bool fceux11_rust_cart_battery_save(const char *path,
                                    const struct FceuSaveGameEntry *entries,
                                    uintptr_t count);

/**
 * Load battery-backed RAM from `path`.  Each non-null entry is read
 * sequentially.  Returns `true` on success (short reads are treated
 * as failure for that entry but the function still returns true if
 * the file could be opened; this matches the original C++ behaviour).
 */
bool fceux11_rust_cart_battery_load(const char *path,
                                    struct FceuSaveGameEntry *entries,
                                    uintptr_t count);

/**
 * Zero-fill all save-game buffers.  Does **not** invoke C++ reset
 * callbacks; the caller must handle those separately.
 */
void fceux11_rust_cart_battery_clear(const struct FceuSaveGameEntry *entries, uintptr_t count);

/**
 * Create a new in-memory EmuFile.
 */
EmuFileMemHandle fceux11_rust_emufile_mem_create(void);

/**
 * Create a new in-memory EmuFile with pre-allocated capacity.
 */
EmuFileMemHandle fceux11_rust_emufile_mem_create_with_capacity(uintptr_t capacity);

/**
 * Create a new in-memory EmuFile from raw bytes.
 */
EmuFileMemHandle fceux11_rust_emufile_mem_create_from_bytes(const uint8_t *ptr, uintptr_t len);

/**
 * Destroy an in-memory EmuFile handle.
 */
void fceux11_rust_emufile_mem_destroy(EmuFileMemHandle handle);

/**
 * Read bytes into C buffer. Returns bytes read.
 */
uintptr_t fceux11_rust_emufile_mem_fread(EmuFileMemHandle handle, uint8_t *ptr, uintptr_t bytes);

/**
 * Write bytes from C buffer. Returns bytes written.
 */
uintptr_t fceux11_rust_emufile_mem_fwrite(EmuFileMemHandle handle,
                                          const uint8_t *ptr,
                                          uintptr_t bytes);

/**
 * Seek within the memory file.
 * origin: 0 = SEEK_SET, 1 = SEEK_CUR, 2 = SEEK_END
 * Returns 0 on success, -1 on failure.
 */
int32_t fceux11_rust_emufile_mem_fseek(EmuFileMemHandle handle, int32_t offset, int32_t origin);

/**
 * Get current position.
 */
uint32_t fceux11_rust_emufile_mem_ftell(EmuFileMemHandle handle);

/**
 * Get size of memory buffer.
 */
uint32_t fceux11_rust_emufile_mem_size(EmuFileMemHandle handle);

/**
 * Truncate the memory buffer.
 */
void fceux11_rust_emufile_mem_truncate(EmuFileMemHandle handle, uint32_t length);

/**
 * Check fail bit (always false in Rust, kept for API parity).
 */
int32_t fceux11_rust_emufile_mem_fail(EmuFileMemHandle handle);

/**
 * Returns non-zero if at EOF.
 */
int32_t fceux11_rust_emufile_mem_eof(EmuFileMemHandle handle);

/**
 * Get read-only data pointer.
 */
const uint8_t *fceux11_rust_emufile_mem_data_ptr(EmuFileMemHandle handle);

/**
 * Ungetc: step position back by one.
 */
void fceux11_rust_emufile_mem_unget(EmuFileMemHandle handle);

/**
 * Read a u8 value.
 */
uint8_t fceux11_rust_emufile_mem_read8(EmuFileMemHandle handle);

/**
 * Write a u8 value.
 */
void fceux11_rust_emufile_mem_write8(EmuFileMemHandle handle, uint8_t val);

/**
 * Read a u16 LE.
 */
uint16_t fceux11_rust_emufile_mem_read16le(EmuFileMemHandle handle);

/**
 * Write a u16 LE.
 */
void fceux11_rust_emufile_mem_write16le(EmuFileMemHandle handle, uint16_t val);

/**
 * Read a u32 LE.
 */
uint32_t fceux11_rust_emufile_mem_read32le(EmuFileMemHandle handle);

/**
 * Write a u32 LE.
 */
void fceux11_rust_emufile_mem_write32le(EmuFileMemHandle handle, uint32_t val);

/**
 * Read a u64 LE.
 */
uint64_t fceux11_rust_emufile_mem_read64le(EmuFileMemHandle handle);

/**
 * Write a u64 LE.
 */
void fceux11_rust_emufile_mem_write64le(EmuFileMemHandle handle, uint64_t val);

/**
 * Clean garbage signatures out of an iNES header.
 * `header_bytes` must point to at least 16 writable bytes.
 */
void fceux11_rust_ines_header_cleanup(uint8_t *header_bytes);

/**
 * Return the human-readable name for a mapper number.
 * Returns a pointer to a static string, or null if not found.
 */
const char *fceux11_rust_ines_mapper_name(int32_t mapper_no);

/**
 * Returns 1 if the mapper is in the not_power2 list.
 */
int32_t fceux11_rust_ines_not_power2(int32_t mapper_no);

/**
 * Look up default input controllers by ROM CRC32.
 * Returns 1 if found, 0 otherwise. Results are written to out_* params.
 */
int32_t fceux11_rust_ines_lookup_input_crc(uint32_t crc32,
                                           int32_t *out_input1,
                                           int32_t *out_input2,
                                           int32_t *out_inputfc);

/**
 * Look up default input controllers by NES 2.0 expansion device byte.
 * Returns 1 if found, 0 otherwise.
 * `out_eoptions_flag` is set to 32768 when expansion == 0x02 (Four-Score hack).
 * `out_vs_cswitch` is set to 1 when expansion == 0x05.
 */
int32_t fceux11_rust_ines_lookup_input_nes20(uint8_t expansion,
                                             int32_t *out_input1,
                                             int32_t *out_input2,
                                             int32_t *out_inputfc,
                                             int32_t *out_eoptions_flag,
                                             int32_t *out_vs_cswitch);

/**
 * Check whether a ROM is known to be bad/corrupt/hacked.
 * Returns a pointer to a static description string, or null if OK.
 */
const char *fceux11_rust_ines_check_bad(uint64_t md5partial);

/**
 * Check ROM-correction databases and return recommended fixes.
 * C++ applies the fixes to its global state.
 */
int32_t fceux11_rust_ines_check_hinfo(uint32_t crc32,
                                      uint64_t partialmd5,
                                      struct FceuInesHInfoResult *out);

/**
 * Look up a UNIF board by name.
 * Returns a pointer to a static `UnifBoardInfo` if found, or null otherwise.
 */
const struct UnifBoardInfo *fceux11_rust_unif_lookup_board(const char *name);

/**
 * Return the hardware flags for a given UNIF board name.
 * Returns -1 if the board is not found.
 */
int32_t fceux11_rust_unif_board_flags(const char *name);

/**
 * Compute CHR-RAM size in bytes from board flags.
 */
uint32_t fceux11_rust_unif_chrram_size(int32_t flags);

/**
 * Look up a VS UniSystem game by its partial MD5 hash.
 * Returns a pointer to a static `VsUniEntry` if found, or null otherwise.
 */
const struct VsUniEntry *fceux11_rust_vsuni_lookup(uint64_t md5partial);

/**
 * Toggle a DIP switch bit. Returns the new vsdip value.
 */
uint8_t fceux11_rust_vsuni_toggle_dip(uint8_t game_type, uint8_t vsdip, int32_t w);

/**
 * Return coin-on duration (6 frames) for a slot.
 */
uint8_t fceux11_rust_vsuni_coin(uint8_t game_type, uint8_t _slot);

/**
 * Return service-button duration (6 frames).
 */
uint8_t fceux11_rust_vsuni_service(uint8_t game_type);

/**
 * Draw the VS UniSystem DIP-switch overlay into the pixel buffer.
 * Returns the decremented `dips_howlong` value (or -1 if nothing drawn).
 */
int32_t fceux11_rust_vsuni_draw(uint8_t *xbuf, uint8_t vsdip, int32_t dips_howlong);
#ifdef __cplusplus
}
#endif

#endif /* FCEUX11_RUST_H */
