
// Stub implementation for git info symbols required by linked Qt driver code.
// The real implementation is generated by genGitHdr.bat for the main executable.

const char *fceu_get_git_url(void) {
    return "unknown";
}

const char *fceu_get_git_rev(void) {
    return "unknown";
}
