// KagamiQA Task 1 (mapper) — Thin C++ shim for the Rust mapper
// byte-diff harness.
//
// Replaces tests/core/mapper_byte_diff_test.cpp once parity (C++ vs
// Rust over the 175 mapper cases in fixtures/golden_mapper/) is
// verified. The Rust side provides:
//   extern "C" int kagami_qa_mapper_byte_diff_main(int argc, const char** argv);
// implemented in src/rust/crates/kagami-qa/src/runner/mapper_byte_diff.rs
// and re-exported by src/rust/src/lib.rs (fceux11_rust.lib).
//
// Usage is identical to the C++ runner:
//   kagami_qa_mapper_byte_diff_runner   (verify mode)
//   (the retired C++ runner accepted --generate for golden regeneration;
//    regenerate goldens before removing the C++ harness)
//
// NOTE: the Rust harness implements VERIFY mode only. --generate is not
// forwarded (goldens are regenerated by the C++ harness before its
// deletion; the Rust harness reads fixtures/golden_mapper/*.bin).

#include <cstdio>
#include <cstring>

extern "C" {
    /// Entry point into the Rust kagami-qa mapper byte-diff harness
    /// (direct mode).
    int kagami_qa_mapper_byte_diff_main(int argc, const char** argv);
}

int main(int argc, char** argv) {
    // The Rust harness is verify-only; a --generate request is rejected
    // explicitly rather than silently running verify mode.
    for (int i = 1; i < argc; ++i) {
        if (std::strcmp(argv[i], "--generate") == 0) {
            std::fprintf(stderr,
                "mapper_byte_diff_rust_main: --generate is not supported by the "
                "Rust harness; regenerate goldens with the C++ harness before "
                "its removal.\n");
            return 2;
        }
    }
    return kagami_qa_mapper_byte_diff_main(argc, const_cast<const char**>(argv));
}
