#!/usr/bin/env python3
"""Generate src/ops_table.inc from src/ops.inc.

Each opcode becomes a standalone function in a std::array function-pointer table.
The original switch body is preserved verbatim except trailing `break;` is removed
and a final `return;` is appended.  The generated file is intended to be included
in src/x6502.cpp after the addressing-mode/operation macros are defined.
"""
import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OPS_INC = PROJECT_ROOT / "src" / "ops.inc"
OUT_INC = PROJECT_ROOT / "src" / "ops_table.inc"

CASE_RE = re.compile(r"^case\s+(0x[0-9A-Fa-f]{2})\s*:")


def parse_ops_inc(text: str):
    """Return dict opcode_int -> body_text."""
    lines = text.splitlines()
    bodies: dict[int, str] = {}
    current_labels: list[int] = []
    current_body_lines: list[str] = []
    body_started = False

    def flush():
        nonlocal current_labels, current_body_lines, body_started
        if not current_labels:
            return
        body = "\n".join(current_body_lines)
        # Remove trailing break; if present so we can统一 append return.
        # The original switch body used break; to exit the switch.  In a
        # standalone function we want to fall through to the trailing return.
        body = re.sub(r"\bbreak\s*;", "", body)
        body = body.rstrip()
        for op in current_labels:
            bodies[op] = body
        current_labels = []
        current_body_lines = []
        body_started = False

    for raw_line in lines:
        line = raw_line.rstrip()
        if not line.strip():
            continue
        m = CASE_RE.search(line)
        if m:
            op = int(m.group(1), 16)
            if body_started:
                # Previous body ended; flush it.
                flush()
            current_labels.append(op)
            # Code after the colon on the same line belongs to the body.
            rest = line[m.end():]
            if rest.strip() and not rest.strip().startswith("/*"):
                current_body_lines.append(rest)
                body_started = True
            elif rest.strip().startswith("/*"):
                # comment-only continuation line; do not mark body started yet
                pass
            continue

        if current_labels:
            current_body_lines.append(line)
            body_started = True

    flush()
    return bodies


def generate():
    ops_text = OPS_INC.read_text(encoding="utf-8")
    bodies = parse_ops_inc(ops_text)

    if len(bodies) != 256:
        missing = [f"0x{i:02X}" for i in range(256) if i not in bodies]
        raise RuntimeError(f"Expected 256 opcodes, got {len(bodies)}. Missing: {missing}")

    out = ["// Auto-generated by scripts/generate_x6502_dispatch.py from src/ops.inc",
           "// Do not edit manually; rerun the generator after ops.inc changes.",
           "",
           "#include <array>",
           "",
           "// Per-opcode handlers. Each shadows the global X with a local reference",
           "// so the existing _PC / _A / ... macros from x6502abbrev.h keep working.",
           ""]

    for i in range(256):
        body = bodies[i]
        out.append(f"static void x6502_op_{i:02X}(X6502* xp)")
        out.append("{")
        out.append("    X6502& X = *xp;")
        if body:
            # Preserve relative indentation from ops.inc.
            for ln in body.splitlines():
                out.append("    " + ln)
        out.append("    return;")
        out.append("}")
        out.append("")

    out.append("static const std::array<void(*)(X6502*), 256> x6502_dispatch = {{")
    row = []
    for i in range(256):
        row.append(f"    x6502_op_{i:02X}")
        if len(row) == 16:
            out.append(",".join(row) + ",")
            row = []
    if row:
        out.append(",".join(row) + ",")
    out.append("}};")
    out.append("")

    OUT_INC.write_text("\n".join(out), encoding="utf-8")
    print(f"Generated {OUT_INC} ({len(bodies)} opcode handlers)")


if __name__ == "__main__":
    generate()
