//! Phase 4 synthetic rendering tests.
//!
//! These tests verify that `rendering::render_scanline` produces the
//! expected pixel output for a known scenario: a 2x2 tile pattern
//! with a simple pattern-table layout. The goal is to pin down the
//! per-pixel color, attribute, palette, mirroring, and grayscale
//! paths in isolation from any CPU/mapper activity.

use fceux11_ppu::rendering::render_scanline;
use fceux11_ppu::state::PpuState;
use fceux11_ppu::registers::{ctrl_bits, mask_bits};
use fceux11_ppu::bus::FlatBus;

#[test]
fn render_solid_color_pattern() {
    // Scenario: 32 nametable tiles all pointing to CHR tile 0, which
    // is a solid-color pattern (all 1s on both planes). With
    // attribute = 0 and palette[0] = 0x00, the output is 0.
    // With palette[0] = 0x16, the output is 0x16 across the row.
    let mut state = PpuState::new();
    // 8x8 solid color tile at CHR tile 0.
    let mut chr = [0u8; 8192];
    for i in 0..16 {
        chr[i] = 0xFF; // all 1s on both planes
    }
    // Nametable: all entries = 0 (pointing to tile 0).
    let mut nt = [0u8; 2048];
    // Attribute table: all zeros (palette 0 for all tiles).
    // The first 64 bytes of NT are the nametable; the next 64 are
    // the attribute table (interleaved at offset 0x3C0).
    // Layout: NT[0..=0x3BF] = name, NT[0x3C0..=0x3FF] = attribute.
    // Our nt array is the 2 KiB window, so we mirror accordingly.
    // Page 0: $2000-$23BF = name (960 bytes), $23C0-$23FF = attr (64 bytes).
    // Page 1: $2400-$27BF = name, $27C0-$27FF = attr.
    // We fill the name portion with zeros (tile 0) and attr with zeros.
    // Already done by nt = [0; 2048].

    // Palette: $3F00 = 0x16 (the visible color).
    let palette = [0x16u8; 32];

    // Set up the PPU: BG pattern = $0000, BG show on, no grayscale.
    state.registers.write_ctrl(0 << ctrl_bits::BG_PATTERN); // $0000
    state.registers.write_mask(1 << mask_bits::SHOW_BG);
    // Set v to scanline 0, with fine_y = 0.
    state.scanline = 0;
    state.dot = 0;
    state.registers.v = 0x2000; // top-left of nametable
    state.registers.t = 0x2000;

    let mut fb = [0u8; 256 * 256];
    let mut bus = FlatBus::new();
    render_scanline(&mut state, &mut bus, &nt, &chr, &palette, 0, &mut fb);

    // The output should be 0x16 across the row.
    for x in 0..256 {
        assert_eq!(
            fb[x as usize], 0x16,
            "pixel x={} should be 0x16 (solid palette[0])", x
        );
    }
}

#[test]
fn render_attribute_quadrant() {
    // Scenario: 2x2 tile block, each tile has a different palette
    // quadrant. Verify the attribute extraction is correct.
    // CHR tile 0 is solid color (all 1s on both planes).
    let mut chr = [0u8; 8192];
    for i in 0..16 {
        chr[i] = 0xFF;
    }
    let mut nt = [0u8; 2048];
    // Attribute byte at $23C0: top-left=0, top-right=1,
    // bottom-left=2, bottom-right=3. (Quadrants 0..3.)
    // Bit layout: cc = 0b11_10_01_00 = 0xE4.
    nt[0x3C0] = 0xE4;

    // Palette: each palette index = its own value.
    // palette[0] = 0x00 (universal BG), palette[1] = 0x01, ..., palette[15] = 0x0F.
    // For pattern 0xFF (all 1s on both planes), the 2-bit color = 3
    // (binary 11). So palette[3] = 0x03 is the visible color for the
    // top-left quadrant test, etc.
    let mut palette = [0u8; 32];
    for i in 0..16 {
        palette[i] = i as u8;
    }

    let mut state = PpuState::new();
    state.registers.write_ctrl(0 << ctrl_bits::BG_PATTERN);
    state.registers.write_mask(1 << mask_bits::SHOW_BG);
    state.scanline = 0;
    state.dot = 0;
    state.registers.v = 0x2000; // top-left of nametable
    state.registers.t = 0x2000;

    let mut fb = [0u8; 256 * 256];
    let mut bus = FlatBus::new();
    render_scanline(&mut state, &mut bus, &nt, &chr, &palette, 0, &mut fb);

    // The Rust renderer replicates the C++ ppu.cpp `atlatch` quirk:
    // a tile's last 4 pixels (XOffset 4..7) use the NEXT tile's
    // attribute quadrant. This is intentional for bit-exact matching
    // with the golden frames (which were generated by the C++ code).
    //
    // For 0xE4 attribute byte = 0b11_10_01_00:
    //   coarse_x 0..1: top-left = bits 0..1 = 0
    //   coarse_x 2..3: top-right = bits 2..3 = 1
    //   coarse_x 4..5: next attribute byte, top-left = 0 (since
    //                  attr is uniform 0xE4 across the table)
    //   coarse_x 6..7: next attribute byte, top-right = 1
    //
    // With the C++ quirk:
    //   Tile 0 (x1=2): pixels 0..3 = attr at coarse_x=0 = 0 (top-left).
    //                   pixels 4..7 = attr at coarse_x=1 = 0 (top-left).
    //                   �?all 8 pixels = 0x03.
    //   Tile 1 (x1=3): pixels 0..3 = attr at coarse_x=1 = 0 (top-left).
    //                   pixels 4..7 = attr at coarse_x=2 = 1 (top-right)
    //                   �?pixels 0..3 = 0x03, pixels 4..7 = 0x07.
    //   Tile 2 (x1=4): pixels 0..3 = attr at coarse_x=2 = 1.
    //                   pixels 4..7 = attr at coarse_x=3 = 1.
    //                   �?all 8 pixels = 0x07.
    //   Tile 3 (x1=5): pixels 0..3 = attr at coarse_x=3 = 1.
    //                   pixels 4..7 = attr at coarse_x=4 = 0 (new attr byte).
    //                   �?pixels 0..3 = 0x07, pixels 4..7 = 0x03.
    for px in 0..8 {
        // Tile 0 (x=0..7): all 0x03.
        assert_eq!(fb[0 * 8 + px], 0x03, "tile 0 px {} should be 0x03", px);
    }
    for px in 0..4 {
        // Tile 1 (x=8..11): 0x03.
        assert_eq!(fb[1 * 8 + px], 0x03, "tile 1 px {} (lo) should be 0x03", px);
    }
    for px in 4..8 {
        // Tile 1 (x=12..15): 0x07 (C++ quirk: next tile's attr).
        assert_eq!(fb[1 * 8 + px], 0x07, "tile 1 px {} (hi) should be 0x07 (quirk)", px);
    }
    for px in 0..8 {
        // Tile 2 (x=16..23): all 0x07.
        assert_eq!(fb[2 * 8 + px], 0x07, "tile 2 px {} should be 0x07", px);
    }
    for px in 0..4 {
        // Tile 3 (x=24..27): 0x07.
        assert_eq!(fb[3 * 8 + px], 0x07, "tile 3 px {} (lo) should be 0x07", px);
    }
    for px in 4..8 {
        // Tile 3 (x=28..31): 0x03 (C++ quirk: next attr byte's first quadrant).
        assert_eq!(fb[3 * 8 + px], 0x03, "tile 3 px {} (hi) should be 0x03 (new attr byte)", px);
    }
}

#[test]
fn render_rendering_off_returns_zero() {
    // When BG is disabled (mask bit 3 = 0), the output should be
    // 0x00 (background color) regardless of pattern data.
    let mut state = PpuState::new();
    let chr = [0u8; 8192];
    let nt = [0u8; 2048];
    let palette = [0u8; 32]; // all 0s

    state.registers.write_mask(0); // no rendering
    state.scanline = 0;
    state.dot = 0;
    state.registers.v = 0x2000;
    state.registers.t = 0x2000;

    let mut fb = [0u8; 256 * 256];
    let mut bus = FlatBus::new();
    render_scanline(&mut state, &mut bus, &nt, &chr, &palette, 0, &mut fb);

    // When BG is off, the renderer skips pixel output, so the
    // framebuffer remains 0.
    for x in 0..256 {
        assert_eq!(fb[x as usize], 0, "pixel x={} should be 0 (rendering off)", x);
    }
}

#[test]
fn render_grayscale_masks_palette() {
    // When grayscale is on (mask bit 0 = 1), the palette value is
    // ANDed with 0x30 to produce a desaturated color.
    let mut state = PpuState::new();
    let mut chr = [0u8; 8192];
    for i in 0..16 {
        chr[i] = 0xFF;
    }
    let nt = [0u8; 2048];
    let mut palette = [0u8; 32];
    // Pattern 0xFF �?2-bit color = 3. With attr=0, palette index = 3.
    // Set palette[3] = 0x3F (max NES palette color); in grayscale
    // mode, this is masked to 0x30.
    palette[3] = 0x3F;

    state.registers.write_ctrl(0 << ctrl_bits::BG_PATTERN);
    state.registers.write_mask(1 << mask_bits::SHOW_BG | 1 << mask_bits::GRAYSCALE);
    state.scanline = 0;
    state.dot = 0;
    state.registers.v = 0x2000;
    state.registers.t = 0x2000;

    let mut fb = [0u8; 256 * 256];
    let mut bus = FlatBus::new();
    render_scanline(&mut state, &mut bus, &nt, &chr, &palette, 0, &mut fb);

    for x in 0..256 {
        assert_eq!(
            fb[x as usize], 0x30,
            "grayscale pixel x={} should be 0x30 (palette masked)", x
        );
    }
}

#[test]
fn render_mirroring_horizontal() {
    // NT page 2 ($2800) should mirror to page 0 in horizontal mode.
    // We set v to page 2 and verify the output is the same as page 0.
    let mut state = PpuState::new();
    let mut chr = [0u8; 8192];
    for i in 0..16 {
        chr[i] = 0xFF;
    }
    let mut nt = [0u8; 2048];
    // Put a non-zero color in page 0's tile 0.
    // (Default is 0, which renders palette[0].)
    // We'll use palette[0] = 0x10 to make it visible.
    let mut palette = [0u8; 32];
    // Pattern 0xFF �?color = 3, attr = 0 �?palette index = 3.
    palette[3] = 0x10;

    state.registers.write_ctrl(0 << ctrl_bits::BG_PATTERN);
    state.registers.write_mask(1 << mask_bits::SHOW_BG);
    state.scanline = 0;
    state.dot = 0;
    // v = $2800 = page 2. In horizontal mode, this mirrors to page 0.
    state.registers.v = 0x2800;
    state.registers.t = 0x2800;

    let mut fb = [0u8; 256 * 256];
    let mut bus = FlatBus::new();
    render_scanline(&mut state, &mut bus, &nt, &chr, &palette, 0, &mut fb);

    for x in 0..256 {
        assert_eq!(
            fb[x as usize], 0x10,
            "horizontal mirror: pixel x={} should be 0x10 (page 2 mirrors page 0)", x
        );
    }
}
