// vNESU11 C-ABI bridge implementation — Phase 0.
//
// Wraps the vNESU11 extern "C" surface so C++ can drive it without
// including the cbindgen-generated header. Phase 6 will expand this
// to cover FCEUI_* compat shims and the full emulation entry points.

#include "vnesu11_bridge.h"

#include <cstdio>
#include <cstdlib>

// vNESU11 extern "C" surface — generated by cbindgen from crates/vnesu11/
// at build time (see crates/vnesu11/build.rs + cbindgen.toml). Output path:
// src/rust/crates/vnesu11/target/vnesu11_ffi.h (relative to the build dir).
// Phase 6 will fold this into the merged `fceux11_rust.h`.
#include "vnesu11_ffi.h"

namespace fceu11 {

void* g_vnesu11_soc = nullptr;

void vnesu11_init(void) {
    if (g_vnesu11_soc) return;
    g_vnesu11_soc = vnesu11_create();
    if (!g_vnesu11_soc) {
        std::fprintf(stderr, "vnesu11_bridge: vnesu11_create() failed\n");
    }
}

void vnesu11_kill(void) {
    if (g_vnesu11_soc) {
        vnesu11_destroy(g_vnesu11_soc);
        g_vnesu11_soc = nullptr;
    }
}

}  // namespace fceu11

// ---------------------------------------------------------------------------
// Bridge functions (thin trampolines)
// ---------------------------------------------------------------------------

void* vnesu11_create_bridge(void) {
    return vnesu11_create();
}

void vnesu11_destroy_bridge(void* soc) {
    vnesu11_destroy(soc);
}

void vnesu11_power_on_bridge(void* soc) {
    vnesu11_power_on(soc);
}

void vnesu11_reset_bridge(void* soc) {
    vnesu11_reset(soc);
}

int vnesu11_set_read_handler_bridge(void* soc, uint16_t start, uint16_t end,
                                    uint8_t (*fn)(void*, uint16_t),
                                    void* ctx) {
    return vnesu11_set_read_handler(soc, start, end,
                                    reinterpret_cast<uint8_t (*)(void*, uint16_t)>(fn),
                                    ctx);
}

int vnesu11_set_write_handler_bridge(void* soc, uint16_t start, uint16_t end,
                                     void (*fn)(void*, uint16_t, uint8_t),
                                     void* ctx) {
    return vnesu11_set_write_handler(soc, start, end,
                                     reinterpret_cast<void (*)(void*, uint16_t, uint8_t)>(fn),
                                     ctx);
}

void vnesu11_clear_mapper_handlers_bridge(void* soc) {
    vnesu11_clear_mapper_handlers(soc);
}

// Phase 0 §1.4: route fceu.cpp::Emulate through this trampoline when
// VNESU11_CORE is enabled. Phase 0 stub: writes nothing, reports 0 samples.
// Phase 1+ wires real emulation through vnesu11_emulate_frame().
void vnesu11_emulate_frame_bridge(
    void* soc, int skip,
    uint8_t* xbuf, int16_t* sbuf, size_t sbuf_cap, size_t* sbuf_written)
{
    if (!soc || !sbuf_written) return;
    if (sbuf_cap > 0 && sbuf) sbuf[0] = 0;  // touch buffer to avoid UB
    if (xbuf) {
        // Don't touch xbuf content (caller may have a partial frame from a
        // previous legacy emulate — Phase 6 will overwrite properly).
    }
    *sbuf_written = 0;
    // The actual call to vnesu11_emulate_frame would go here in Phase 6+.
    // Phase 0 leaves it as a no-op so the C++ Emulate path remains
    // functional under VNESU11_CORE_ENABLED.
    (void)skip;
}
