//! Phase 4: per-scanline BG + sprite renderer for the 2C02 PPU.
//!
//! Replicates the C++ new PPU's `pputile.inc` algorithm
//! (`src/pputile_template.cpp::FetchAndDrawTile<kFNormal>`, the path
//! used for NROM). One call per visible scanline (from `tick_dot` at
//! sl 0..239 dot 0) renders 256 pixels as 32 tiles of 8 pixels each.
//!
//! ## Algorithm
//!
//! For each of 32 tiles (with 2 pre-loads and 1 next-tile preload):
//! 1. Render 8 pixels using `pshift[0..2]` + the per-pixel attribute
//!    from the C++ `atlatch` quirk (see below).
//! 2. Fetch the next tile's NT byte, AT byte, PT_LO byte, PT_HI byte.
//! 3. Update `atlatch`, shift `pshift <<= 8`, OR the new pattern.
//! 4. Increment coarse X (with horizontal nametable flip).
//!
//! The first two tiles are pre-loads (no render), the next 30 are
//! the visible render iterations, and the 33rd-34th pre-load for the
//! next scanline. The shift register / atlatch persist across
//! scanlines.
//!
//! ## The `atlatch` quirk
//!
//! The C++ algorithm uses a `u32 atlatch` that accumulates two
//! attribute quadrants across iterations: the current tile's quadrant
//! in bits 0..1 and the next tile's quadrant in bits 2..3, with
//! `atlatch >>= 2; atlatch |= cc << 2` per iteration. The render
//! uses `ppulut3[XOffset | (atlatch << 3)]`, which extracts
//! pixels 0..3 from bits 0..1 of atlatch (the current tile's
//! quadrant) and pixels 4..7 from bits 2..3 (the next tile's
//! quadrant). This is a quirk of the FCEUX algorithm: a tile's last
//! 4 pixels use the NEXT tile's attribute. The golden frames in
//! `tests/fixtures/golden_frames` were generated by the C++ algorithm
//! and include this quirk, so we replicate it for bit-exact matching.

use crate::bus::PpuBus;
use crate::registers::mask_bits;
use crate::state::PpuState;
#[cfg(test)]
use crate::luts::{PPULUT1, PPULUT2};

/// Number of tiles fetched per visible scanline (32 visible + 2
/// preloads). Two preloads populate the shift register with the
/// previous scanline's last two tiles (or zero on the first frame).
const TILES_PER_SCANLINE: usize = 34;
/// Number of pixels per tile.
const PIXELS_PER_TILE: usize = 8;
/// Number of visible pixels per scanline.
const VISIBLE_PIXELS: usize = 256;
/// Bit 0 of $2001: grayscale.
const GRAYSCALE: u8 = 1 << 0;
/// Bit 3 of $2001: show BG.
const SHOW_BG: u8 = 1 << 3;
/// Bit 4 of $2000: BG pattern table select.
const BG_PATTERN_BIT: u8 = 1 << 4;

/// Replicates the C++ `PaletteAdjustPixel` XBuf byte format
/// (`src/ppu_rendering.cpp:1524-1531`). The framebuffer the bridge
/// copies into XBuf must carry the same high-bit flags as the C++
/// new PPU's output: no emphasis → `(color & 0x3F) | 0x80`, any
/// emphasis (not all three) → `color | 0x40`, all three emphasis
/// bits ($2001 >> 5 == 0x7) → `(color & 0x3F) | 0xC0`.
pub fn palette_adjust_pixel(color: u8, mask: u8) -> u8 {
    if (mask >> 5) == 0x7 {
        (color & 0x3F) | 0xC0
    } else if (mask & 0xE0) != 0 {
        color | 0x40
    } else {
        (color & 0x3F) | 0x80
    }
}

/// Maps a 14-bit VRAM address to the corresponding 1 KiB nametable
/// page, applying the configured mirroring mode. Returns the index
/// into the 2 KiB NT window.
fn map_nametable_addr(v: u16, mode: u8) -> u16 {
    let nt = ((v >> 10) & 0x3) as u16;
    let coarse = v & 0x03FF;
    let mapped_nt: u16 = match mode {
        0 => nt & 0x1,
        1 => nt >> 1,
        2 => 0,
        3 => 1,
        4 => nt,
        _ => nt,
    };
    (mapped_nt << 10) | coarse
}

/// Extract the 2-bit palette quadrant from a single attribute byte,
/// given the tile's coarse X and the bit-1 of coarse Y.
fn attribute_quadrant(at_byte: u8, coarse_x: u16, coarse_y_bit1: u8) -> u8 {
    let shift = ((coarse_x & 2) + (coarse_y_bit1 as u16 & 0x4)) as u8;
    (at_byte >> shift) & 0x3
}

/// Render one visible scanline's 256 pixels into the framebuffer.
///
/// The NT window is the full 4 KiB the C++ bridge installs
/// (`ppu_rust_bridge_power` copies vnapage[0..4]): the four-screen
/// mirror mode (mode 4) maps addresses across the whole 0x0000-0x0FFF
/// range, so a 2 KiB view would read out of bounds for four-screen
/// mappers (MMC5 etc.).
pub fn render_scanline<B: PpuBus + ?Sized>(
    state: &mut PpuState,
    _bus: &mut B,
    nt_window: &[u8; 4096],
    chr_window: &[u8; 8192],
    palette: &[u8; 32],
    mirror_mode: u8,
    framebuffer: &mut [u8; 256 * 256],
) {
    let sl = state.scanline;
    if !(0..=239).contains(&sl) {
        return;
    }
    let mask = state.registers.mask;
    let bg_show = (mask & SHOW_BG) != 0;
    let sprite_show = (mask & (1 << mask_bits::SHOW_SPRITES)) != 0;
    let grayscale = (mask & GRAYSCALE) != 0;
    let fine_x = (state.registers.fine_x & 0x07) as u32;
    let bg_pattern_base: u16 = if state.registers.ctrl & BG_PATTERN_BIT != 0 {
        0x1000
    } else {
        0x0000
    };

    let mut pshift = state.bg_pshift;
    let mut atlatch: u32 = state.bg_atlatch as u32;
    let mut v = state.registers.v;
    let row_off = (sl as usize) * 256;

    // Rendering-disabled fill (C++ new-PPU blank path,
    // `src/ppu_rendering.cpp:1841-1886`). Every visible scanline is
    // written every frame even when BG display is off, so a frame
    // with $2001 rendering bits cleared shows the backdrop color
    // instead of stale framebuffer content. With ScreenON and
    // SpriteON both clear the C++ reads the pixel from $2006's value
    // (`get_2007access`) when it points into palette RAM; indices
    // $04/$08/$0C read back through UPALRAM in C++, which PowerNES
    // initializes identical to our window's mirrored entries, so a
    // direct PALRAM lookup matches for all reachable states.
    if !bg_show {
        let pix: usize = if !sprite_show && (v & 0x3F00) == 0x3F00 {
            (v & 0x1F) as usize
        } else {
            0
        };
        let gray_mask: u8 = if grayscale { 0x30 } else { 0xFF };
        let out = palette_adjust_pixel(palette[pix] & gray_mask, mask);
        framebuffer[row_off..row_off + VISIBLE_PIXELS].fill(out);
    }

    for x1 in 0..TILES_PER_SCANLINE {
        // Step 1: render 8 pixels of the current tile (skip the two
        // pre-loads at x1=0,1 and the next-tile preload at x1=32,33).
        if x1 >= 2 && x1 < 34 && bg_show {
            // The C++ uses `atlatch` as a 4-bit value indexed into
            // the LUT. We replicate that here.
            //
            // Pixels 0..3 use bits 0..1 of atlatch.
            // Pixels 4..7 use bits 2..3 of atlatch.
            // (When XOffset < 4, the LUT formula `(cc >> 0) & 3` extracts
            // bits 0..1. When XOffset >= 4, `(cc >> 2) & 3` extracts
            // bits 2..3.)
            for px in 0..PIXELS_PER_TILE {
                let bit_pos: i32 = 15 - fine_x as i32 - px as i32;
                let pat0 = if bit_pos >= 0 {
                    ((pshift[0] >> bit_pos) & 1) as u8
                } else {
                    0
                };
                let pat1 = if bit_pos >= 0 {
                    ((pshift[1] >> bit_pos) & 1) as u8
                } else {
                    0
                };
                let color_2bit = pat0 | (pat1 << 1);
                // Extract per-pixel attribute from atlatch.
                let shiftr: u32 = if px < 4 { 0 } else { 2 };
                let attr_quadrant = ((atlatch >> shiftr) & 0x3) as u8;
                let color_4bit = color_2bit | (attr_quadrant << 2);
                let gray_mask: u8 = if grayscale { 0x30 } else { 0xFF };
                let pal_idx = if color_4bit == 0 {
                    palette[0] & gray_mask
                } else {
                    palette[color_4bit as usize] & gray_mask
                };
                let out_idx = (x1 - 2) * PIXELS_PER_TILE + px;
                if out_idx < VISIBLE_PIXELS {
                    framebuffer[row_off + out_idx] = palette_adjust_pixel(pal_idx, mask);
                }
            }
        }

        // Step 2: fetch the next tile's NT, AT, PT_LO, PT_HI.
        let nt_addr = map_nametable_addr(v, mirror_mode);
        let nt_byte = nt_window[nt_addr as usize];

        // Attribute address: 0x23C0 | (nt << 10) | (coarse_x / 4)
        // | (coarse_y / 4) * 8.
        let coarse_x_at = v & 0x1F;
        let coarse_y_at = (v >> 5) & 0x1F;
        let nt_page = ((v >> 10) & 0x3) as u16;
        let at_addr_offset =
            (((coarse_x_at >> 2) & 0x7) as u16) + (((coarse_y_at >> 2) & 0x7) as u16) * 8;
        let at_addr = 0x3C0 + (nt_page << 10) + at_addr_offset;
        let at_mapped = map_nametable_addr(at_addr, mirror_mode);
        let at_byte = nt_window[at_mapped as usize];
        let coarse_y_bit1 = ((coarse_y_at & 0x2) << 1) as u8;
        let cc = attribute_quadrant(at_byte, coarse_x_at, coarse_y_bit1);

        // CHR address: bg_pattern_base + (nt_byte << 4) + fine_y.
        let fine_y = ((v >> 12) & 0x7) as usize;
        let chr_lo_addr = (bg_pattern_base as usize) + (nt_byte as usize) * 16 + fine_y;
        let chr_hi_addr = chr_lo_addr + 8;
        let pt_lo = chr_window[chr_lo_addr & 0x1FFF];
        let pt_hi = chr_window[chr_hi_addr & 0x1FFF];

        // Step 3: update atlatch (shift right by 2, OR cc << 2).
        atlatch = (atlatch >> 2) | ((cc as u32) << 2);

        // Step 4: shift pshift <<= 8; OR new pattern.
        pshift[0] = (pshift[0] << 8) | (pt_lo as u16);
        pshift[1] = (pshift[1] << 8) | (pt_hi as u16);

        // Step 5: increment coarse X with horizontal nametable flip.
        let new_coarse_x = (v & 0x1F) + 1;
        if new_coarse_x & 0x20 != 0 {
            v = (v & !0x001F) ^ 0x0400;
        } else {
            v = (v & !0x001F) | (new_coarse_x & 0x1F);
        }
    }

    // Persist pshift and atlatch for the next scanline's preload.
    state.bg_pshift = pshift;
    state.bg_atlatch = (atlatch & 0xFF) as u8;
    state.registers.v = v;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn map_nametable_horizontal() {
        assert_eq!(map_nametable_addr(0x2000, 0), 0x0000);
        assert_eq!(map_nametable_addr(0x2400, 0), 0x0400);
        assert_eq!(map_nametable_addr(0x2800, 0), 0x0000);
        assert_eq!(map_nametable_addr(0x2C00, 0), 0x0400);
    }

    #[test]
    fn map_nametable_vertical() {
        assert_eq!(map_nametable_addr(0x2000, 1), 0x0000);
        assert_eq!(map_nametable_addr(0x2400, 1), 0x0000);
        assert_eq!(map_nametable_addr(0x2800, 1), 0x0400);
        assert_eq!(map_nametable_addr(0x2C00, 1), 0x0400);
    }

    #[test]
    fn map_nametable_four_screen() {
        assert_eq!(map_nametable_addr(0x2000, 4), 0x0000);
        assert_eq!(map_nametable_addr(0x2400, 4), 0x0400);
        assert_eq!(map_nametable_addr(0x2800, 4), 0x0800);
        assert_eq!(map_nametable_addr(0x2C00, 4), 0x0C00);
    }

    #[test]
    fn palette_adjust_pixel_matches_cpp() {
        // C++ PaletteAdjustPixel (src/ppu_rendering.cpp:1524-1531):
        // no emphasis → (color & 0x3F) | 0x80, any emphasis but not
        // all three → color | 0x40, all three ($2001>>5==0x7) →
        // (color & 0x3F) | 0xC0.
        assert_eq!(palette_adjust_pixel(0x16, 0x00), 0x96);
        assert_eq!(palette_adjust_pixel(0x30, 0x01), 0xB0); // grayscale set, no emphasis
        let any_emph = 0x20; // red only
        assert_eq!(palette_adjust_pixel(0x16, any_emph), 0x56);
        let two_emph = 0xA0; // green+blue
        assert_eq!(palette_adjust_pixel(0x3F, two_emph), 0x7F);
        let all_emph = 0xE0;
        assert_eq!(palette_adjust_pixel(0xFF, all_emph), 0xFF);
    }

    #[test]
    fn attribute_quadrant_layout() {
        assert_eq!(attribute_quadrant(0xCC, 0, 0), 0); // top-left
        assert_eq!(attribute_quadrant(0xCC, 2, 0), 3); // top-right
        assert_eq!(attribute_quadrant(0xCC, 0, 4), 0); // bottom-left
        assert_eq!(attribute_quadrant(0xCC, 2, 4), 3); // bottom-right
    }

    #[test]
    fn ppulut1_basic() {
        assert_eq!(PPULUT1[0x80] & 0xF, 1);
        assert_eq!(PPULUT1[0xFF] & 0xF, 1);
        assert_eq!((PPULUT1[0xFF] >> 28) & 0xF, 1);
    }

    #[test]
    fn ppulut2_basic() {
        assert_eq!(PPULUT2[0x80] & 0xF, 2);
        assert_eq!(PPULUT2[0xFF] & 0xF, 2);
    }
}
