<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<!--
  v0.3.15 PR-B i18n baseline.
  Generated by lupdate from src/drivers/Qt/**/*.cpp; 3,481 source entries.
  The "type=unfinished" entries are the source strings awaiting zh_CN/zh_TW
  machine translation in PR-C. They are NOT to be hand-edited in this file.
  Use Qt Linguist to translate fceux11_zh_CN.ts / fceux11_zh_TW.ts.

  This baseline is intentionally empty; it will be re-populated by
  `lupdate -project translations.pro` after the PR-B CMake migration lands.
-->
<context>
    <name>consoleWin_t</name>
    <message>
        <source>&amp;File</source>
        <translation>&amp;File</translation>
    </message>
    <message>
        <source>&amp;Emulation</source>
        <translation>&amp;Emulation</translation>
    </message>
    <message>
        <source>&amp;Options</source>
        <translation>&amp;Options</translation>
    </message>
    <message>
        <source>&amp;Help</source>
        <translation>&amp;Help</translation>
    </message>
    <message>
        <source>&amp;Advanced</source>
        <translation>&amp;Advanced</translation>
    </message>
    <message>
        <source>&amp;Language</source>
        <translation>&amp;Language</translation>
    </message>
    <message>
        <source>&amp;Open ROM</source>
        <translation>&amp;Open ROM</translation>
    </message>
    <message>
        <source>&amp;Close ROM</source>
        <translation>&amp;Close ROM</translation>
    </message>
    <message>
        <source>&amp;Recent ROMs</source>
        <translation>&amp;Recent ROMs</translation>
    </message>
    <message>
        <source>Play &amp;NSF</source>
        <translation>Play &amp;NSF</translation>
    </message>
    <message>
        <source>Load State &amp;From</source>
        <translation>Load State &amp;From</translation>
    </message>
    <message>
        <source>Save State &amp;As</source>
        <translation>Save State &amp;As</translation>
    </message>
    <message>
        <source>Quick &amp;Load</source>
        <translation>Quick &amp;Load</translation>
    </message>
    <message>
        <source>Quick &amp;Save</source>
        <translation>Quick &amp;Save</translation>
    </message>
    <message>
        <source>Load &amp;Lua Script</source>
        <translation>Load &amp;Lua Script</translation>
    </message>
    <message>
        <source>Screens&amp;hot</source>
        <translation>Screens&amp;hot</translation>
    </message>
    <message>
        <source>&amp;Quit</source>
        <translation>&amp;Quit</translation>
    </message>
    <message>
        <source>&amp;About FCEUX11</source>
        <translation>&amp;About FCEUX11</translation>
    </message>
    <message>
        <source>About &amp;Qt</source>
        <translation>About &amp;Qt</translation>
    </message>
    <message>
        <source>&amp;Message Log</source>
        <translation>&amp;Message Log</translation>
    </message>
</context>
</TS>
